{{- if .Values.clusterapioutscale.mutatingWebhook.enable }}
  {{ $root := . }}
  {{- with .Values.clusterapioutscale.mutatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ $root.Release.Namespace }}/{{ template "clusterapioutscale.fullname" $root }}-serving-cert
  name: {{ template "clusterapioutscale.mutatingwebhook" $root }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "clusterapioutscale.webhookservice" $root }}
      namespace:  {{ $root.Release.Namespace }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-oscclustertemplate
  failurePolicy: Fail
  name: moscclustertemplate.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oscclustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "clusterapioutscale.webhookservice" $root }}
      namespace: {{ $root.Release.Namespace }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-oscmachine
  failurePolicy: Fail
  name: moscmachine.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oscmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ template "clusterapioutscale.webhookservice" $root }}
      namespace: {{ $root.Release.Namespace }}
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-oscmachinetemplate
  failurePolicy: Fail
  name: moscmachinetemplate.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oscmachinetemplates
  sideEffects: None
  {{- end }}
{{- end }} 
