{{- if .Values.clusterapioutscale.proxyClusterRoleBinding.enable }}
  {{ $root := . }}
  {{- with .Values.clusterapioutscale.proxyClusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    control-plane: "{{ template "clusterapioutscale.controllermanager" $root }}"
    app: "{{ template "clusterapioutscale.fullname" $root }}"
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    release: "{{ $root.Release.Name }}"
  name: {{ template "clusterapioutscale.proxyClusterRoleBinding" $root }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "clusterapioutscale.proxyClusterRoleBinding" $root }}
subjects:
- kind: ServiceAccount
  name: {{ template "clusterapioutscale.serviceAccount" $root }}
  namespace: {{ $root.Release.Namespace }}
  {{- end }}
{{- end }} 
