{{- if .Values.clusterapioutscale.serviceAccount.enable }}
  {{ $root := . }}
  {{- with .Values.clusterapioutscale.serviceAccount.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "clusterapioutscale.serviceAccount" $root }}
  namespace: {{ $root.Release.Namespace }}
  {{- end }}
{{- end }}
