// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -destination mock_tag/tag_mock.go -package mock_tag -source ./service.go
//

// Package mock_tag is a generated GoMock package.
package mock_tag

import (
	context "context"
	reflect "reflect"

	tag "github.com/outscale/cluster-api-provider-outscale/cloud/services/tag"
	osc "github.com/outscale/osc-sdk-go/v3/pkg/osc"
	gomock "go.uber.org/mock/gomock"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
	isgomock struct{}
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// AddTag mocks base method.
func (m *MockServicer) AddTag(ctx context.Context, req osc.CreateTagsRequest, resourceIds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", ctx, req, resourceIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTag indicates an expected call of AddTag.
func (mr *MockServicerMockRecorder) AddTag(ctx, req, resourceIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockServicer)(nil).AddTag), ctx, req, resourceIds)
}

// ReadOwnedByTag mocks base method.
func (m *MockServicer) ReadOwnedByTag(ctx context.Context, rsrcType tag.ResourceType, cluster string) (*osc.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOwnedByTag", ctx, rsrcType, cluster)
	ret0, _ := ret[0].(*osc.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOwnedByTag indicates an expected call of ReadOwnedByTag.
func (mr *MockServicerMockRecorder) ReadOwnedByTag(ctx, rsrcType, cluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOwnedByTag", reflect.TypeOf((*MockServicer)(nil).ReadOwnedByTag), ctx, rsrcType, cluster)
}

// ReadTag mocks base method.
func (m *MockServicer) ReadTag(ctx context.Context, rsrcType tag.ResourceType, key, value string) (*osc.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTag", ctx, rsrcType, key, value)
	ret0, _ := ret[0].(*osc.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTag indicates an expected call of ReadTag.
func (mr *MockServicerMockRecorder) ReadTag(ctx, rsrcType, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTag", reflect.TypeOf((*MockServicer)(nil).ReadTag), ctx, rsrcType, key, value)
}
