// Code generated by MockGen. DO NOT EDIT.
// Source: ./internetservice.go

// Package mock_net is a generated GoMock package.
package mock_net

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	osc "github.com/outscale/osc-sdk-go/v2"
)

// MockOscInternetServiceInterface is a mock of OscInternetServiceInterface interface.
type MockOscInternetServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscInternetServiceInterfaceMockRecorder
}

// MockOscInternetServiceInterfaceMockRecorder is the mock recorder for MockOscInternetServiceInterface.
type MockOscInternetServiceInterfaceMockRecorder struct {
	mock *MockOscInternetServiceInterface
}

// NewMockOscInternetServiceInterface creates a new mock instance.
func NewMockOscInternetServiceInterface(ctrl *gomock.Controller) *MockOscInternetServiceInterface {
	mock := &MockOscInternetServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOscInternetServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscInternetServiceInterface) EXPECT() *MockOscInternetServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateInternetService mocks base method.
func (m *MockOscInternetServiceInterface) CreateInternetService(ctx context.Context, internetServiceName string) (*osc.InternetService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInternetService", ctx, internetServiceName)
	ret0, _ := ret[0].(*osc.InternetService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInternetService indicates an expected call of CreateInternetService.
func (mr *MockOscInternetServiceInterfaceMockRecorder) CreateInternetService(ctx, internetServiceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInternetService", reflect.TypeOf((*MockOscInternetServiceInterface)(nil).CreateInternetService), ctx, internetServiceName)
}

// DeleteInternetService mocks base method.
func (m *MockOscInternetServiceInterface) DeleteInternetService(ctx context.Context, internetServiceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInternetService", ctx, internetServiceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInternetService indicates an expected call of DeleteInternetService.
func (mr *MockOscInternetServiceInterfaceMockRecorder) DeleteInternetService(ctx, internetServiceId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInternetService", reflect.TypeOf((*MockOscInternetServiceInterface)(nil).DeleteInternetService), ctx, internetServiceId)
}

// GetInternetService mocks base method.
func (m *MockOscInternetServiceInterface) GetInternetService(ctx context.Context, internetServiceId string) (*osc.InternetService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInternetService", ctx, internetServiceId)
	ret0, _ := ret[0].(*osc.InternetService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInternetService indicates an expected call of GetInternetService.
func (mr *MockOscInternetServiceInterfaceMockRecorder) GetInternetService(ctx, internetServiceId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInternetService", reflect.TypeOf((*MockOscInternetServiceInterface)(nil).GetInternetService), ctx, internetServiceId)
}

// LinkInternetService mocks base method.
func (m *MockOscInternetServiceInterface) LinkInternetService(ctx context.Context, internetServiceId, netId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkInternetService", ctx, internetServiceId, netId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkInternetService indicates an expected call of LinkInternetService.
func (mr *MockOscInternetServiceInterfaceMockRecorder) LinkInternetService(ctx, internetServiceId, netId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkInternetService", reflect.TypeOf((*MockOscInternetServiceInterface)(nil).LinkInternetService), ctx, internetServiceId, netId)
}

// UnlinkInternetService mocks base method.
func (m *MockOscInternetServiceInterface) UnlinkInternetService(ctx context.Context, internetServiceId, netId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkInternetService", ctx, internetServiceId, netId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkInternetService indicates an expected call of UnlinkInternetService.
func (mr *MockOscInternetServiceInterfaceMockRecorder) UnlinkInternetService(ctx, internetServiceId, netId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkInternetService", reflect.TypeOf((*MockOscInternetServiceInterface)(nil).UnlinkInternetService), ctx, internetServiceId, netId)
}
