// Code generated by MockGen. DO NOT EDIT.
// Source: ./natservice.go

// Package mock_net is a generated GoMock package.
package mock_net

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	osc "github.com/outscale/osc-sdk-go/v2"
)

// MockOscNatServiceInterface is a mock of OscNatServiceInterface interface.
type MockOscNatServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscNatServiceInterfaceMockRecorder
}

// MockOscNatServiceInterfaceMockRecorder is the mock recorder for MockOscNatServiceInterface.
type MockOscNatServiceInterfaceMockRecorder struct {
	mock *MockOscNatServiceInterface
}

// NewMockOscNatServiceInterface creates a new mock instance.
func NewMockOscNatServiceInterface(ctrl *gomock.Controller) *MockOscNatServiceInterface {
	mock := &MockOscNatServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOscNatServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscNatServiceInterface) EXPECT() *MockOscNatServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateNatService mocks base method.
func (m *MockOscNatServiceInterface) CreateNatService(ctx context.Context, publicIpId, subnetId, natServiceName, clusterName string) (*osc.NatService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNatService", ctx, publicIpId, subnetId, natServiceName, clusterName)
	ret0, _ := ret[0].(*osc.NatService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNatService indicates an expected call of CreateNatService.
func (mr *MockOscNatServiceInterfaceMockRecorder) CreateNatService(ctx, publicIpId, subnetId, natServiceName, clusterName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNatService", reflect.TypeOf((*MockOscNatServiceInterface)(nil).CreateNatService), ctx, publicIpId, subnetId, natServiceName, clusterName)
}

// DeleteNatService mocks base method.
func (m *MockOscNatServiceInterface) DeleteNatService(ctx context.Context, natServiceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNatService", ctx, natServiceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNatService indicates an expected call of DeleteNatService.
func (mr *MockOscNatServiceInterfaceMockRecorder) DeleteNatService(ctx, natServiceId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNatService", reflect.TypeOf((*MockOscNatServiceInterface)(nil).DeleteNatService), ctx, natServiceId)
}

// GetNatService mocks base method.
func (m *MockOscNatServiceInterface) GetNatService(ctx context.Context, natServiceId string) (*osc.NatService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatService", ctx, natServiceId)
	ret0, _ := ret[0].(*osc.NatService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatService indicates an expected call of GetNatService.
func (mr *MockOscNatServiceInterfaceMockRecorder) GetNatService(ctx, natServiceId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatService", reflect.TypeOf((*MockOscNatServiceInterface)(nil).GetNatService), ctx, natServiceId)
}
