// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -destination mock_net/net_mock.go -package mock_net -source ./service.go
//

// Package mock_net is a generated GoMock package.
package mock_net

import (
	context "context"
	reflect "reflect"

	v1beta2 "github.com/outscale/cluster-api-provider-outscale/api/v1beta2"
	osc "github.com/outscale/osc-sdk-go/v3/pkg/osc"
	gomock "go.uber.org/mock/gomock"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
	isgomock struct{}
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// AcceptNetPeering mocks base method.
func (m *MockServicer) AcceptNetPeering(ctx context.Context, netPeeringID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptNetPeering", ctx, netPeeringID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptNetPeering indicates an expected call of AcceptNetPeering.
func (mr *MockServicerMockRecorder) AcceptNetPeering(ctx, netPeeringID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptNetPeering", reflect.TypeOf((*MockServicer)(nil).AcceptNetPeering), ctx, netPeeringID)
}

// ConfigureHealthCheck mocks base method.
func (m *MockServicer) ConfigureHealthCheck(ctx context.Context, spec *v1beta2.OscLoadBalancer) (*osc.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureHealthCheck", ctx, spec)
	ret0, _ := ret[0].(*osc.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfigureHealthCheck indicates an expected call of ConfigureHealthCheck.
func (mr *MockServicerMockRecorder) ConfigureHealthCheck(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureHealthCheck", reflect.TypeOf((*MockServicer)(nil).ConfigureHealthCheck), ctx, spec)
}

// CreateInternetService mocks base method.
func (m *MockServicer) CreateInternetService(ctx context.Context, internetServiceName, clusterID string) (*osc.InternetService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInternetService", ctx, internetServiceName, clusterID)
	ret0, _ := ret[0].(*osc.InternetService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInternetService indicates an expected call of CreateInternetService.
func (mr *MockServicerMockRecorder) CreateInternetService(ctx, internetServiceName, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInternetService", reflect.TypeOf((*MockServicer)(nil).CreateInternetService), ctx, internetServiceName, clusterID)
}

// CreateLoadBalancer mocks base method.
func (m *MockServicer) CreateLoadBalancer(ctx context.Context, spec *v1beta2.OscLoadBalancer, subnetId, securityGroupId string) (*osc.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancer", ctx, spec, subnetId, securityGroupId)
	ret0, _ := ret[0].(*osc.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoadBalancer indicates an expected call of CreateLoadBalancer.
func (mr *MockServicerMockRecorder) CreateLoadBalancer(ctx, spec, subnetId, securityGroupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancer", reflect.TypeOf((*MockServicer)(nil).CreateLoadBalancer), ctx, spec, subnetId, securityGroupId)
}

// CreateLoadBalancerTag mocks base method.
func (m *MockServicer) CreateLoadBalancerTag(ctx context.Context, spec *v1beta2.OscLoadBalancer, loadBalancerTag *osc.ResourceTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancerTag", ctx, spec, loadBalancerTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLoadBalancerTag indicates an expected call of CreateLoadBalancerTag.
func (mr *MockServicerMockRecorder) CreateLoadBalancerTag(ctx, spec, loadBalancerTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancerTag", reflect.TypeOf((*MockServicer)(nil).CreateLoadBalancerTag), ctx, spec, loadBalancerTag)
}

// CreateNatService mocks base method.
func (m *MockServicer) CreateNatService(ctx context.Context, publicIpId, subnetId, clientToken, natServiceName, clusterID string) (*osc.NatService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNatService", ctx, publicIpId, subnetId, clientToken, natServiceName, clusterID)
	ret0, _ := ret[0].(*osc.NatService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNatService indicates an expected call of CreateNatService.
func (mr *MockServicerMockRecorder) CreateNatService(ctx, publicIpId, subnetId, clientToken, natServiceName, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNatService", reflect.TypeOf((*MockServicer)(nil).CreateNatService), ctx, publicIpId, subnetId, clientToken, natServiceName, clusterID)
}

// CreateNet mocks base method.
func (m *MockServicer) CreateNet(ctx context.Context, spec v1beta2.OscNet, clusterID, netName string) (*osc.Net, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNet", ctx, spec, clusterID, netName)
	ret0, _ := ret[0].(*osc.Net)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNet indicates an expected call of CreateNet.
func (mr *MockServicerMockRecorder) CreateNet(ctx, spec, clusterID, netName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNet", reflect.TypeOf((*MockServicer)(nil).CreateNet), ctx, spec, clusterID, netName)
}

// CreateNetAccessPoint mocks base method.
func (m *MockServicer) CreateNetAccessPoint(ctx context.Context, netId, region, service string, rtblIds []string, clusterID string) (*osc.NetAccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetAccessPoint", ctx, netId, region, service, rtblIds, clusterID)
	ret0, _ := ret[0].(*osc.NetAccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetAccessPoint indicates an expected call of CreateNetAccessPoint.
func (mr *MockServicerMockRecorder) CreateNetAccessPoint(ctx, netId, region, service, rtblIds, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetAccessPoint", reflect.TypeOf((*MockServicer)(nil).CreateNetAccessPoint), ctx, netId, region, service, rtblIds, clusterID)
}

// CreateNetPeering mocks base method.
func (m *MockServicer) CreateNetPeering(ctx context.Context, netID, mgmtNetID, mgmtAccountID, clusterID string) (*osc.NetPeering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetPeering", ctx, netID, mgmtNetID, mgmtAccountID, clusterID)
	ret0, _ := ret[0].(*osc.NetPeering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetPeering indicates an expected call of CreateNetPeering.
func (mr *MockServicerMockRecorder) CreateNetPeering(ctx, netID, mgmtNetID, mgmtAccountID, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetPeering", reflect.TypeOf((*MockServicer)(nil).CreateNetPeering), ctx, netID, mgmtNetID, mgmtAccountID, clusterID)
}

// CreatePublicIp mocks base method.
func (m *MockServicer) CreatePublicIp(ctx context.Context, publicIpName, clusterID string) (*osc.PublicIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePublicIp", ctx, publicIpName, clusterID)
	ret0, _ := ret[0].(*osc.PublicIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePublicIp indicates an expected call of CreatePublicIp.
func (mr *MockServicerMockRecorder) CreatePublicIp(ctx, publicIpName, clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePublicIp", reflect.TypeOf((*MockServicer)(nil).CreatePublicIp), ctx, publicIpName, clusterID)
}

// CreateRoute mocks base method.
func (m *MockServicer) CreateRoute(ctx context.Context, destinationIpRange, routeTableId, resourceId, targetType string) (*osc.RouteTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoute", ctx, destinationIpRange, routeTableId, resourceId, targetType)
	ret0, _ := ret[0].(*osc.RouteTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoute indicates an expected call of CreateRoute.
func (mr *MockServicerMockRecorder) CreateRoute(ctx, destinationIpRange, routeTableId, resourceId, targetType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoute", reflect.TypeOf((*MockServicer)(nil).CreateRoute), ctx, destinationIpRange, routeTableId, resourceId, targetType)
}

// CreateRouteTable mocks base method.
func (m *MockServicer) CreateRouteTable(ctx context.Context, netId, clusterID, routeTableName string) (*osc.RouteTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRouteTable", ctx, netId, clusterID, routeTableName)
	ret0, _ := ret[0].(*osc.RouteTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRouteTable indicates an expected call of CreateRouteTable.
func (mr *MockServicerMockRecorder) CreateRouteTable(ctx, netId, clusterID, routeTableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRouteTable", reflect.TypeOf((*MockServicer)(nil).CreateRouteTable), ctx, netId, clusterID, routeTableName)
}

// CreateSubnet mocks base method.
func (m *MockServicer) CreateSubnet(ctx context.Context, spec v1beta2.OscSubnet, netId, clusterID, subnetName string) (*osc.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnet", ctx, spec, netId, clusterID, subnetName)
	ret0, _ := ret[0].(*osc.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubnet indicates an expected call of CreateSubnet.
func (mr *MockServicerMockRecorder) CreateSubnet(ctx, spec, netId, clusterID, subnetName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnet", reflect.TypeOf((*MockServicer)(nil).CreateSubnet), ctx, spec, netId, clusterID, subnetName)
}

// DeleteInternetService mocks base method.
func (m *MockServicer) DeleteInternetService(ctx context.Context, internetServiceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInternetService", ctx, internetServiceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInternetService indicates an expected call of DeleteInternetService.
func (mr *MockServicerMockRecorder) DeleteInternetService(ctx, internetServiceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInternetService", reflect.TypeOf((*MockServicer)(nil).DeleteInternetService), ctx, internetServiceId)
}

// DeleteLoadBalancer mocks base method.
func (m *MockServicer) DeleteLoadBalancer(ctx context.Context, spec *v1beta2.OscLoadBalancer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", ctx, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockServicerMockRecorder) DeleteLoadBalancer(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockServicer)(nil).DeleteLoadBalancer), ctx, spec)
}

// DeleteLoadBalancerTag mocks base method.
func (m *MockServicer) DeleteLoadBalancerTag(ctx context.Context, spec *v1beta2.OscLoadBalancer, loadBalancerTag osc.ResourceLoadBalancerTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancerTag", ctx, spec, loadBalancerTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancerTag indicates an expected call of DeleteLoadBalancerTag.
func (mr *MockServicerMockRecorder) DeleteLoadBalancerTag(ctx, spec, loadBalancerTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancerTag", reflect.TypeOf((*MockServicer)(nil).DeleteLoadBalancerTag), ctx, spec, loadBalancerTag)
}

// DeleteNatService mocks base method.
func (m *MockServicer) DeleteNatService(ctx context.Context, natServiceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNatService", ctx, natServiceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNatService indicates an expected call of DeleteNatService.
func (mr *MockServicerMockRecorder) DeleteNatService(ctx, natServiceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNatService", reflect.TypeOf((*MockServicer)(nil).DeleteNatService), ctx, natServiceId)
}

// DeleteNet mocks base method.
func (m *MockServicer) DeleteNet(ctx context.Context, netId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNet", ctx, netId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNet indicates an expected call of DeleteNet.
func (mr *MockServicerMockRecorder) DeleteNet(ctx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNet", reflect.TypeOf((*MockServicer)(nil).DeleteNet), ctx, netId)
}

// DeleteNetAccessPoint mocks base method.
func (m *MockServicer) DeleteNetAccessPoint(ctx context.Context, netAccessPointId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetAccessPoint", ctx, netAccessPointId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetAccessPoint indicates an expected call of DeleteNetAccessPoint.
func (mr *MockServicerMockRecorder) DeleteNetAccessPoint(ctx, netAccessPointId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetAccessPoint", reflect.TypeOf((*MockServicer)(nil).DeleteNetAccessPoint), ctx, netAccessPointId)
}

// DeleteNetPeering mocks base method.
func (m *MockServicer) DeleteNetPeering(ctx context.Context, netPeeringID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetPeering", ctx, netPeeringID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetPeering indicates an expected call of DeleteNetPeering.
func (mr *MockServicerMockRecorder) DeleteNetPeering(ctx, netPeeringID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetPeering", reflect.TypeOf((*MockServicer)(nil).DeleteNetPeering), ctx, netPeeringID)
}

// DeletePublicIp mocks base method.
func (m *MockServicer) DeletePublicIp(ctx context.Context, publicIpId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePublicIp", ctx, publicIpId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePublicIp indicates an expected call of DeletePublicIp.
func (mr *MockServicerMockRecorder) DeletePublicIp(ctx, publicIpId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePublicIp", reflect.TypeOf((*MockServicer)(nil).DeletePublicIp), ctx, publicIpId)
}

// DeleteRoute mocks base method.
func (m *MockServicer) DeleteRoute(ctx context.Context, destinationIpRange, routeTableId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoute", ctx, destinationIpRange, routeTableId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoute indicates an expected call of DeleteRoute.
func (mr *MockServicerMockRecorder) DeleteRoute(ctx, destinationIpRange, routeTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoute", reflect.TypeOf((*MockServicer)(nil).DeleteRoute), ctx, destinationIpRange, routeTableId)
}

// DeleteRouteTable mocks base method.
func (m *MockServicer) DeleteRouteTable(ctx context.Context, routeTableId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRouteTable", ctx, routeTableId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRouteTable indicates an expected call of DeleteRouteTable.
func (mr *MockServicerMockRecorder) DeleteRouteTable(ctx, routeTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRouteTable", reflect.TypeOf((*MockServicer)(nil).DeleteRouteTable), ctx, routeTableId)
}

// DeleteSubnet mocks base method.
func (m *MockServicer) DeleteSubnet(ctx context.Context, subnetId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnet", ctx, subnetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnet indicates an expected call of DeleteSubnet.
func (mr *MockServicerMockRecorder) DeleteSubnet(ctx, subnetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnet", reflect.TypeOf((*MockServicer)(nil).DeleteSubnet), ctx, subnetId)
}

// GetInternetService mocks base method.
func (m *MockServicer) GetInternetService(ctx context.Context, internetServiceId string) (*osc.InternetService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInternetService", ctx, internetServiceId)
	ret0, _ := ret[0].(*osc.InternetService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInternetService indicates an expected call of GetInternetService.
func (mr *MockServicerMockRecorder) GetInternetService(ctx, internetServiceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInternetService", reflect.TypeOf((*MockServicer)(nil).GetInternetService), ctx, internetServiceId)
}

// GetInternetServiceForNet mocks base method.
func (m *MockServicer) GetInternetServiceForNet(ctx context.Context, netId string) (*osc.InternetService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInternetServiceForNet", ctx, netId)
	ret0, _ := ret[0].(*osc.InternetService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInternetServiceForNet indicates an expected call of GetInternetServiceForNet.
func (mr *MockServicerMockRecorder) GetInternetServiceForNet(ctx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInternetServiceForNet", reflect.TypeOf((*MockServicer)(nil).GetInternetServiceForNet), ctx, netId)
}

// GetLoadBalancer mocks base method.
func (m *MockServicer) GetLoadBalancer(ctx context.Context, loadBalancerName string) (*osc.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancer", ctx, loadBalancerName)
	ret0, _ := ret[0].(*osc.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancer indicates an expected call of GetLoadBalancer.
func (mr *MockServicerMockRecorder) GetLoadBalancer(ctx, loadBalancerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancer", reflect.TypeOf((*MockServicer)(nil).GetLoadBalancer), ctx, loadBalancerName)
}

// GetNatService mocks base method.
func (m *MockServicer) GetNatService(ctx context.Context, natServiceId string) (*osc.NatService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatService", ctx, natServiceId)
	ret0, _ := ret[0].(*osc.NatService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatService indicates an expected call of GetNatService.
func (mr *MockServicerMockRecorder) GetNatService(ctx, natServiceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatService", reflect.TypeOf((*MockServicer)(nil).GetNatService), ctx, natServiceId)
}

// GetNatServiceFromClientToken mocks base method.
func (m *MockServicer) GetNatServiceFromClientToken(ctx context.Context, clientToken string) (*osc.NatService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatServiceFromClientToken", ctx, clientToken)
	ret0, _ := ret[0].(*osc.NatService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatServiceFromClientToken indicates an expected call of GetNatServiceFromClientToken.
func (mr *MockServicerMockRecorder) GetNatServiceFromClientToken(ctx, clientToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatServiceFromClientToken", reflect.TypeOf((*MockServicer)(nil).GetNatServiceFromClientToken), ctx, clientToken)
}

// GetNet mocks base method.
func (m *MockServicer) GetNet(ctx context.Context, netId string) (*osc.Net, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNet", ctx, netId)
	ret0, _ := ret[0].(*osc.Net)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNet indicates an expected call of GetNet.
func (mr *MockServicerMockRecorder) GetNet(ctx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNet", reflect.TypeOf((*MockServicer)(nil).GetNet), ctx, netId)
}

// GetNetAccessPoint mocks base method.
func (m *MockServicer) GetNetAccessPoint(ctx context.Context, netAccessPointId string) (*osc.NetAccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetAccessPoint", ctx, netAccessPointId)
	ret0, _ := ret[0].(*osc.NetAccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetAccessPoint indicates an expected call of GetNetAccessPoint.
func (mr *MockServicerMockRecorder) GetNetAccessPoint(ctx, netAccessPointId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetAccessPoint", reflect.TypeOf((*MockServicer)(nil).GetNetAccessPoint), ctx, netAccessPointId)
}

// GetNetAccessPointFor mocks base method.
func (m *MockServicer) GetNetAccessPointFor(ctx context.Context, netId, region, service string) (*osc.NetAccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetAccessPointFor", ctx, netId, region, service)
	ret0, _ := ret[0].(*osc.NetAccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetAccessPointFor indicates an expected call of GetNetAccessPointFor.
func (mr *MockServicerMockRecorder) GetNetAccessPointFor(ctx, netId, region, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetAccessPointFor", reflect.TypeOf((*MockServicer)(nil).GetNetAccessPointFor), ctx, netId, region, service)
}

// GetNetPeering mocks base method.
func (m *MockServicer) GetNetPeering(ctx context.Context, netPeeringID string) (*osc.NetPeering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetPeering", ctx, netPeeringID)
	ret0, _ := ret[0].(*osc.NetPeering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetPeering indicates an expected call of GetNetPeering.
func (mr *MockServicerMockRecorder) GetNetPeering(ctx, netPeeringID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetPeering", reflect.TypeOf((*MockServicer)(nil).GetNetPeering), ctx, netPeeringID)
}

// GetNetPeeringFromNet mocks base method.
func (m *MockServicer) GetNetPeeringFromNet(ctx context.Context, netID, mgmtNetID, mgmtAccountID string) (*osc.NetPeering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetPeeringFromNet", ctx, netID, mgmtNetID, mgmtAccountID)
	ret0, _ := ret[0].(*osc.NetPeering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetPeeringFromNet indicates an expected call of GetNetPeeringFromNet.
func (mr *MockServicerMockRecorder) GetNetPeeringFromNet(ctx, netID, mgmtNetID, mgmtAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetPeeringFromNet", reflect.TypeOf((*MockServicer)(nil).GetNetPeeringFromNet), ctx, netID, mgmtNetID, mgmtAccountID)
}

// GetPublicIp mocks base method.
func (m *MockServicer) GetPublicIp(ctx context.Context, publicIpId string) (*osc.PublicIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicIp", ctx, publicIpId)
	ret0, _ := ret[0].(*osc.PublicIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicIp indicates an expected call of GetPublicIp.
func (mr *MockServicerMockRecorder) GetPublicIp(ctx, publicIpId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicIp", reflect.TypeOf((*MockServicer)(nil).GetPublicIp), ctx, publicIpId)
}

// GetPublicIpByIp mocks base method.
func (m *MockServicer) GetPublicIpByIp(ctx context.Context, publicIp string) (*osc.PublicIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicIpByIp", ctx, publicIp)
	ret0, _ := ret[0].(*osc.PublicIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicIpByIp indicates an expected call of GetPublicIpByIp.
func (mr *MockServicerMockRecorder) GetPublicIpByIp(ctx, publicIp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicIpByIp", reflect.TypeOf((*MockServicer)(nil).GetPublicIpByIp), ctx, publicIp)
}

// GetRouteTable mocks base method.
func (m *MockServicer) GetRouteTable(ctx context.Context, routeTableId string) (*osc.RouteTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteTable", ctx, routeTableId)
	ret0, _ := ret[0].(*osc.RouteTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouteTable indicates an expected call of GetRouteTable.
func (mr *MockServicerMockRecorder) GetRouteTable(ctx, routeTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteTable", reflect.TypeOf((*MockServicer)(nil).GetRouteTable), ctx, routeTableId)
}

// GetRouteTableFromRoute mocks base method.
func (m *MockServicer) GetRouteTableFromRoute(ctx context.Context, routeTableId, resourceId, resourceType string) (*osc.RouteTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteTableFromRoute", ctx, routeTableId, resourceId, resourceType)
	ret0, _ := ret[0].(*osc.RouteTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouteTableFromRoute indicates an expected call of GetRouteTableFromRoute.
func (mr *MockServicerMockRecorder) GetRouteTableFromRoute(ctx, routeTableId, resourceId, resourceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteTableFromRoute", reflect.TypeOf((*MockServicer)(nil).GetRouteTableFromRoute), ctx, routeTableId, resourceId, resourceType)
}

// GetRouteTablesFromNet mocks base method.
func (m *MockServicer) GetRouteTablesFromNet(ctx context.Context, netId string) ([]osc.RouteTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteTablesFromNet", ctx, netId)
	ret0, _ := ret[0].([]osc.RouteTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouteTablesFromNet indicates an expected call of GetRouteTablesFromNet.
func (mr *MockServicerMockRecorder) GetRouteTablesFromNet(ctx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteTablesFromNet", reflect.TypeOf((*MockServicer)(nil).GetRouteTablesFromNet), ctx, netId)
}

// GetSubnet mocks base method.
func (m *MockServicer) GetSubnet(ctx context.Context, subnetId string) (*osc.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnet", ctx, subnetId)
	ret0, _ := ret[0].(*osc.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnet indicates an expected call of GetSubnet.
func (mr *MockServicerMockRecorder) GetSubnet(ctx, subnetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnet", reflect.TypeOf((*MockServicer)(nil).GetSubnet), ctx, subnetId)
}

// GetSubnetFromNet mocks base method.
func (m *MockServicer) GetSubnetFromNet(ctx context.Context, netId, ipRange string) (*osc.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetFromNet", ctx, netId, ipRange)
	ret0, _ := ret[0].(*osc.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetFromNet indicates an expected call of GetSubnetFromNet.
func (mr *MockServicerMockRecorder) GetSubnetFromNet(ctx, netId, ipRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetFromNet", reflect.TypeOf((*MockServicer)(nil).GetSubnetFromNet), ctx, netId, ipRange)
}

// LinkInternetService mocks base method.
func (m *MockServicer) LinkInternetService(ctx context.Context, internetServiceId, netId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkInternetService", ctx, internetServiceId, netId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkInternetService indicates an expected call of LinkInternetService.
func (mr *MockServicerMockRecorder) LinkInternetService(ctx, internetServiceId, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkInternetService", reflect.TypeOf((*MockServicer)(nil).LinkInternetService), ctx, internetServiceId, netId)
}

// LinkLoadBalancerBackendMachines mocks base method.
func (m *MockServicer) LinkLoadBalancerBackendMachines(ctx context.Context, vmIds []string, loadBalancerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkLoadBalancerBackendMachines", ctx, vmIds, loadBalancerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkLoadBalancerBackendMachines indicates an expected call of LinkLoadBalancerBackendMachines.
func (mr *MockServicerMockRecorder) LinkLoadBalancerBackendMachines(ctx, vmIds, loadBalancerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkLoadBalancerBackendMachines", reflect.TypeOf((*MockServicer)(nil).LinkLoadBalancerBackendMachines), ctx, vmIds, loadBalancerName)
}

// LinkRouteTable mocks base method.
func (m *MockServicer) LinkRouteTable(ctx context.Context, routeTableId, subnetId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkRouteTable", ctx, routeTableId, subnetId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkRouteTable indicates an expected call of LinkRouteTable.
func (mr *MockServicerMockRecorder) LinkRouteTable(ctx, routeTableId, subnetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkRouteTable", reflect.TypeOf((*MockServicer)(nil).LinkRouteTable), ctx, routeTableId, subnetId)
}

// ListNatServices mocks base method.
func (m *MockServicer) ListNatServices(tx context.Context, netId string) ([]osc.NatService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNatServices", tx, netId)
	ret0, _ := ret[0].([]osc.NatService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNatServices indicates an expected call of ListNatServices.
func (mr *MockServicerMockRecorder) ListNatServices(tx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNatServices", reflect.TypeOf((*MockServicer)(nil).ListNatServices), tx, netId)
}

// ListNetAccessPoints mocks base method.
func (m *MockServicer) ListNetAccessPoints(ctx context.Context, netId string) ([]osc.NetAccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetAccessPoints", ctx, netId)
	ret0, _ := ret[0].([]osc.NetAccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetAccessPoints indicates an expected call of ListNetAccessPoints.
func (mr *MockServicerMockRecorder) ListNetAccessPoints(ctx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetAccessPoints", reflect.TypeOf((*MockServicer)(nil).ListNetAccessPoints), ctx, netId)
}

// ListNetPeerings mocks base method.
func (m *MockServicer) ListNetPeerings(ctx context.Context, netId string) ([]osc.NetPeering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetPeerings", ctx, netId)
	ret0, _ := ret[0].([]osc.NetPeering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetPeerings indicates an expected call of ListNetPeerings.
func (mr *MockServicerMockRecorder) ListNetPeerings(ctx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetPeerings", reflect.TypeOf((*MockServicer)(nil).ListNetPeerings), ctx, netId)
}

// ListPublicIpsFromPool mocks base method.
func (m *MockServicer) ListPublicIpsFromPool(ctx context.Context, pool string) ([]osc.PublicIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicIpsFromPool", ctx, pool)
	ret0, _ := ret[0].([]osc.PublicIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicIpsFromPool indicates an expected call of ListPublicIpsFromPool.
func (mr *MockServicerMockRecorder) ListPublicIpsFromPool(ctx, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicIpsFromPool", reflect.TypeOf((*MockServicer)(nil).ListPublicIpsFromPool), ctx, pool)
}

// UnlinkInternetService mocks base method.
func (m *MockServicer) UnlinkInternetService(ctx context.Context, internetServiceId, netId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkInternetService", ctx, internetServiceId, netId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkInternetService indicates an expected call of UnlinkInternetService.
func (mr *MockServicerMockRecorder) UnlinkInternetService(ctx, internetServiceId, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkInternetService", reflect.TypeOf((*MockServicer)(nil).UnlinkInternetService), ctx, internetServiceId, netId)
}

// UnlinkLoadBalancerBackendMachines mocks base method.
func (m *MockServicer) UnlinkLoadBalancerBackendMachines(ctx context.Context, vmIds []string, loadBalancerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkLoadBalancerBackendMachines", ctx, vmIds, loadBalancerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkLoadBalancerBackendMachines indicates an expected call of UnlinkLoadBalancerBackendMachines.
func (mr *MockServicerMockRecorder) UnlinkLoadBalancerBackendMachines(ctx, vmIds, loadBalancerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkLoadBalancerBackendMachines", reflect.TypeOf((*MockServicer)(nil).UnlinkLoadBalancerBackendMachines), ctx, vmIds, loadBalancerName)
}

// UnlinkRouteTable mocks base method.
func (m *MockServicer) UnlinkRouteTable(ctx context.Context, linkRouteTableId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkRouteTable", ctx, linkRouteTableId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkRouteTable indicates an expected call of UnlinkRouteTable.
func (mr *MockServicerMockRecorder) UnlinkRouteTable(ctx, linkRouteTableId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkRouteTable", reflect.TypeOf((*MockServicer)(nil).UnlinkRouteTable), ctx, linkRouteTableId)
}
