apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-api
  namespace: default
  labels:
    cni: "cluster-api-crs-cni"
    ccm: "cluster-api-crs-ccm"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.42.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OscCluster
    name: cluster-api
    namespace: default
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "cluster-api-control-plane"
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscCluster
metadata:
  name: cluster-api
  namespace: default
spec:
  network:
    subregionName: eu-west-2a
    loadBalancer:
      loadbalancername: osc-k8s
    bastion:
      enable: false
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: "cluster-api-md-0"
  namespace: default
spec:
  clusterName: "cluster-api"
  replicas: 1
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "cluster-api"
      version: "1.29.1"
      bootstrap:
        configRef:
          name: "cluster-api-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          namespace: default
      infrastructureRef:
        name: "cluster-api-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OscMachineTemplate
        namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: "cluster-api-md-0"
  namespace: default
spec:
  template:
    spec:
      node:
        image:
          name: ubuntu-22.04-2204-kubernetes-v1.29.1-2024-02-19
        vm:
          keypairName: cluster-api
          rootDisk:
            rootDiskSize: 30
            rootDiskType: gp2
          subregionName: eu-west-2a
          vmType: "tinav6.c4r8p2"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: "cluster-api-control-plane"
  namespace: default
spec:
  template:
    spec:
      node:
        image:
         name: ubuntu-22.04-2204-kubernetes-v1.29.1-2024-02-19
        vm:
          keypairName: cluster-api
          rootDisk:
            rootDiskSize: 30
            rootDiskType: gp2
          role: controlplane
          vmType: "tinav5.c4r8p1"
          tags:
              osc.fcu.repulse_server: vm-control-plane
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "cluster-api-md-0"
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: "{{ ds.meta_data.local_hostname }}"
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: aws://'{{ ds.meta_data.placement.availability_zone }}'/'{{ ds.meta_data.instance_id }}'
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "cluster-api-control-plane"
spec:
  replicas: 1
  machineTemplate:
    infrastructureRef:
      kind: OscMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: "cluster-api-control-plane"
      namespace: default
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        taints:
        - key: "key1"
          value: "value1"
          effect: "NoSchedule"
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: aws://'{{ ds.meta_data.placement.availability_zone }}'/'{{ ds.meta_data.instance_id }}'
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        taints:
        - key: "key1"
          value: "value1"
          effect: "NoSchedule"
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: aws://'{{ ds.meta_data.placement.availability_zone }}'/'{{ ds.meta_data.instance_id }}'
  version: "1.29.1"
