---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-api-multi-az
  namespace: default
  labels:
    cni: "cluster-api-multi-az-crs-cni"
    ccm: "cluster-api-multi-az-crs-ccm"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.233.64.0/18"]
    services:
      cidrBlocks: ["10.233.0.0/18"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OscCluster
    name:  cluster-api-multi-az
    namespace: default
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "cluster-api-multi-az-control-plane"
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscCluster
metadata:
  name:  cluster-api-multi-az
  namespace: default
spec:
  network:
    loadBalancer:
      loadbalancername: cluster-api-multi-az-lb
    net:
      ipRange: "10.0.0.0/16"
    subnets:
    - ipSubnetRange: "10.0.0.0/24"
      subregionName: eu-west-2a
      roles:
      - worker
    - ipSubnetRange: "10.0.1.0/24"
      subregionName: eu-west-2b
      roles:
      - worker
    - ipSubnetRange: "10.0.2.0/24"
      subregionName: eu-west-2a
      roles:
      - controlplane
    - ipSubnetRange: "10.0.3.0/24"
      subregionName: eu-west-2b
      roles:
      - controlplane
    - ipSubnetRange: "10.0.4.0/24"
      subregionName: eu-west-2a
      roles:
      - loadbalancer
      - nat
    - ipSubnetRange: "10.0.5.0/24"
      subregionName: eu-west-2b
      roles:
      - nat
    bastion:
      enable: false
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: cluster-api-multi-az-control-plane
  namespace: default
spec:
  template:
    spec:
      node:
        image:
         name: ubuntu-2004-2004-kubernetes-v1.27.7-2023-10-18
        vm:
          name: cluster-api-multi-az-vm-control-plane
          keypairName: cluster-api
          rootDisk:
            rootDiskSize: 50
            rootDiskType: gp2
          role: controlplane
          vmType: "tinav6.c4r8p1"
          tags:
              osc.fcu.repulse_server: vm-control-plane
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: cluster-api-multi-az-control-plane
  namespace: default
spec:
  replicas: 3
  machineTemplate:
    infrastructureRef:
      kind: OscMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      name: cluster-api-multi-az-control-plane
      namespace: default
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: aws:///'{{ ds.meta_data.placement.availability_zone }}'/'{{ ds.meta_data.instance_id }}'
        name: '{{ ds.meta_data.local_hostname }}'
    files:
    - content: |
        #!/bin/sh
        curl https://github.com/opencontainers/runc/releases/download/v1.1.1/runc.amd64 -Lo /tmp/runc.amd64
        chmod +x /tmp/runc.amd64
        cp -f /tmp/runc.amd64 /usr/local/sbin/runc
      owner: root:root
      path: /tmp/set_runc.sh
      permissions: "0744"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: aws:///'{{ ds.meta_data.placement.availability_zone }}'/'{{ ds.meta_data.instance_id }}'
        name: '{{ ds.meta_data.local_hostname }}'
    preKubeadmCommands:
      - sh /tmp/set_runc.sh
  version: "1.29.1"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: cluster-api-multi-az-worker-2a
  namespace: default
spec:
  template:
    spec:
      node:
        image:
         name: ubuntu-2004-2004-kubernetes-v1.27.7-2023-10-18
        vm:
          keypairName: cluster-api
          rootDisk:
            rootDiskSize: 50
            rootDiskType: gp2
          subregionName: eu-west-2a
          vmType: "tinav6.c4r8p2"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OscMachineTemplate
metadata:
  name: cluster-api-multi-az-worker-2b
  namespace: default
spec:
  template:
    spec:
      node:
        image:
         name: ubuntu-2004-2004-kubernetes-v1.27.7-2023-10-18
        vm:
          keypairName: cluster-api
          rootDisk:
            rootDiskSize: 50
            rootDiskType: gp2
          subregionName: eu-west-2b
          vmType: "tinav6.c4r8p2"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "cluster-api-multi-az-worker-config"
  namespace: default
spec:
  template:
    spec:
      files:
      - content: |
          #!/bin/sh
          curl https://github.com/opencontainers/runc/releases/download/v1.1.1/runc.amd64 -Lo /tmp/runc.amd64
          chmod +x /tmp/runc.amd64
          cp -f /tmp/runc.amd64 /usr/local/sbin/runc
        owner: root:root
        path: /tmp/set_runc.sh
        permissions: "0744"
      joinConfiguration:
        nodeRegistration:
          name: "{{ ds.meta_data.local_hostname }}"
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: aws:///'{{ ds.meta_data.placement.availability_zone }}'/'{{ ds.meta_data.instance_id }}'
      preKubeadmCommands:
        - sh /tmp/set_runc.sh
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: cluster-api-multi-az-worker-2a-md
  namespace: default
spec:
  clusterName: cluster-api-multi-az
  replicas: 1
  selector:
    matchLabels:
      node-role: worker
  template:
    metadata:
      labels:
        node-role: worker
    spec:
      clusterName: cluster-api-multi-az
      version: "1.29.1"
      bootstrap:
        configRef:
          name: cluster-api-multi-az-worker-config
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          namespace: default
      infrastructureRef:
        name: cluster-api-multi-az-worker-2a
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OscMachineTemplate
        namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: cluster-api-multi-az-worker-2b-md
  namespace: default
spec:
  clusterName: cluster-api-multi-az
  replicas: 1
  selector:
    matchLabels:
      node-role: worker
  template:
    metadata:
      labels:
        node-role: worker
    spec:
      clusterName: cluster-api-multi-az
      version: "1.22.11"
      bootstrap:
        configRef:
          name: cluster-api-multi-az-worker-config
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          namespace: default
      infrastructureRef:
        name: cluster-api-multi-az-worker-2b
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OscMachineTemplate
        namespace: default
