// Code generated by MockGen. DO NOT EDIT.
// Source: ./tag.go
//
// Generated by this command:
//
//	mockgen -destination mock_tag/tag_mock.go -package mock_tag -source ./tag.go
//

// Package mock_tag is a generated GoMock package.
package mock_tag

import (
	context "context"
	reflect "reflect"

	osc "github.com/outscale/osc-sdk-go/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockOscTagInterface is a mock of OscTagInterface interface.
type MockOscTagInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscTagInterfaceMockRecorder
	isgomock struct{}
}

// MockOscTagInterfaceMockRecorder is the mock recorder for MockOscTagInterface.
type MockOscTagInterfaceMockRecorder struct {
	mock *MockOscTagInterface
}

// NewMockOscTagInterface creates a new mock instance.
func NewMockOscTagInterface(ctrl *gomock.Controller) *MockOscTagInterface {
	mock := &MockOscTagInterface{ctrl: ctrl}
	mock.recorder = &MockOscTagInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscTagInterface) EXPECT() *MockOscTagInterfaceMockRecorder {
	return m.recorder
}

// ReadTag mocks base method.
func (m *MockOscTagInterface) ReadTag(ctx context.Context, tagKey, tagValue string) (*osc.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTag", ctx, tagKey, tagValue)
	ret0, _ := ret[0].(*osc.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTag indicates an expected call of ReadTag.
func (mr *MockOscTagInterfaceMockRecorder) ReadTag(ctx, tagKey, tagValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTag", reflect.TypeOf((*MockOscTagInterface)(nil).ReadTag), ctx, tagKey, tagValue)
}
