// Code generated by MockGen. DO NOT EDIT.
// Source: ./load_balancer.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v1beta2 "github.com/outscale-dev/cluster-api-provider-outscale.git/api/v1beta2"
	osc "github.com/outscale/osc-sdk-go/v2"
)

// MockOscLoadBalancerInterface is a mock of OscLoadBalancerInterface interface.
type MockOscLoadBalancerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscLoadBalancerInterfaceMockRecorder
}

// MockOscLoadBalancerInterfaceMockRecorder is the mock recorder for MockOscLoadBalancerInterface.
type MockOscLoadBalancerInterfaceMockRecorder struct {
	mock *MockOscLoadBalancerInterface
}

// NewMockOscLoadBalancerInterface creates a new mock instance.
func NewMockOscLoadBalancerInterface(ctrl *gomock.Controller) *MockOscLoadBalancerInterface {
	mock := &MockOscLoadBalancerInterface{ctrl: ctrl}
	mock.recorder = &MockOscLoadBalancerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscLoadBalancerInterface) EXPECT() *MockOscLoadBalancerInterfaceMockRecorder {
	return m.recorder
}

// CheckLoadBalancerDeregisterVm mocks base method.
func (m *MockOscLoadBalancerInterface) CheckLoadBalancerDeregisterVm(clockInsideLoop, clockLoop time.Duration, spec *v1beta2.OscLoadBalancer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLoadBalancerDeregisterVm", clockInsideLoop, clockLoop, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckLoadBalancerDeregisterVm indicates an expected call of CheckLoadBalancerDeregisterVm.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) CheckLoadBalancerDeregisterVm(clockInsideLoop, clockLoop, spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLoadBalancerDeregisterVm", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).CheckLoadBalancerDeregisterVm), clockInsideLoop, clockLoop, spec)
}

// ConfigureHealthCheck mocks base method.
func (m *MockOscLoadBalancerInterface) ConfigureHealthCheck(spec *v1beta2.OscLoadBalancer) (*osc.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureHealthCheck", spec)
	ret0, _ := ret[0].(*osc.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfigureHealthCheck indicates an expected call of ConfigureHealthCheck.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) ConfigureHealthCheck(spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureHealthCheck", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).ConfigureHealthCheck), spec)
}

// CreateLoadBalancer mocks base method.
func (m *MockOscLoadBalancerInterface) CreateLoadBalancer(spec *v1beta2.OscLoadBalancer, subnetId, securityGroupId string) (*osc.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancer", spec, subnetId, securityGroupId)
	ret0, _ := ret[0].(*osc.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLoadBalancer indicates an expected call of CreateLoadBalancer.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) CreateLoadBalancer(spec, subnetId, securityGroupId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancer", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).CreateLoadBalancer), spec, subnetId, securityGroupId)
}

// CreateLoadBalancerTag mocks base method.
func (m *MockOscLoadBalancerInterface) CreateLoadBalancerTag(spec *v1beta2.OscLoadBalancer, loadBalancerTag osc.ResourceTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoadBalancerTag", spec, loadBalancerTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLoadBalancerTag indicates an expected call of CreateLoadBalancerTag.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) CreateLoadBalancerTag(spec, loadBalancerTag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoadBalancerTag", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).CreateLoadBalancerTag), spec, loadBalancerTag)
}

// DeleteLoadBalancer mocks base method.
func (m *MockOscLoadBalancerInterface) DeleteLoadBalancer(spec *v1beta2.OscLoadBalancer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancer", spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancer indicates an expected call of DeleteLoadBalancer.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) DeleteLoadBalancer(spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancer", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).DeleteLoadBalancer), spec)
}

// DeleteLoadBalancerTag mocks base method.
func (m *MockOscLoadBalancerInterface) DeleteLoadBalancerTag(spec *v1beta2.OscLoadBalancer, loadBalancerTag osc.ResourceLoadBalancerTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLoadBalancerTag", spec, loadBalancerTag)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLoadBalancerTag indicates an expected call of DeleteLoadBalancerTag.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) DeleteLoadBalancerTag(spec, loadBalancerTag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLoadBalancerTag", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).DeleteLoadBalancerTag), spec, loadBalancerTag)
}

// GetLoadBalancer mocks base method.
func (m *MockOscLoadBalancerInterface) GetLoadBalancer(spec *v1beta2.OscLoadBalancer) (*osc.LoadBalancer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancer", spec)
	ret0, _ := ret[0].(*osc.LoadBalancer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancer indicates an expected call of GetLoadBalancer.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) GetLoadBalancer(spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancer", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).GetLoadBalancer), spec)
}

// GetLoadBalancerTag mocks base method.
func (m *MockOscLoadBalancerInterface) GetLoadBalancerTag(spec *v1beta2.OscLoadBalancer) (*osc.LoadBalancerTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancerTag", spec)
	ret0, _ := ret[0].(*osc.LoadBalancerTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancerTag indicates an expected call of GetLoadBalancerTag.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) GetLoadBalancerTag(spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancerTag", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).GetLoadBalancerTag), spec)
}

// LinkLoadBalancerBackendMachines mocks base method.
func (m *MockOscLoadBalancerInterface) LinkLoadBalancerBackendMachines(vmIds []string, loadBalancerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkLoadBalancerBackendMachines", vmIds, loadBalancerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkLoadBalancerBackendMachines indicates an expected call of LinkLoadBalancerBackendMachines.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) LinkLoadBalancerBackendMachines(vmIds, loadBalancerName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkLoadBalancerBackendMachines", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).LinkLoadBalancerBackendMachines), vmIds, loadBalancerName)
}

// UnlinkLoadBalancerBackendMachines mocks base method.
func (m *MockOscLoadBalancerInterface) UnlinkLoadBalancerBackendMachines(vmIds []string, loadBalancerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkLoadBalancerBackendMachines", vmIds, loadBalancerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkLoadBalancerBackendMachines indicates an expected call of UnlinkLoadBalancerBackendMachines.
func (mr *MockOscLoadBalancerInterfaceMockRecorder) UnlinkLoadBalancerBackendMachines(vmIds, loadBalancerName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkLoadBalancerBackendMachines", reflect.TypeOf((*MockOscLoadBalancerInterface)(nil).UnlinkLoadBalancerBackendMachines), vmIds, loadBalancerName)
}
