name: Bug Report
description: Report a bug enccountered while using cluster-api
title: "[Bug]: "
labels: ["bug"]
assignees:
  - outscale-vbr
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: What happened ?
      placeholder: Explain the bug with a clear and concise description
    validations:
      required: true
  - type: textarea
    id: step
    attributes:
      label: Step to reproduce
      description: What steps did you take (as minimally and precisely as possible to reproduce it)  ?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected to happen
      description: What did you expect to happen ?
    validations:
      required: true
  - type: textarea
    id: Add
    attributes:
      label: Add anything
      description: Anything else you would like to add ?
      placeholder: Miscellaneous information that will help to resolve the issue
    validations:
      required: true
  - type: textarea
    id: cluster-api-output
    attributes:
      label: cluster-api output
      description: cluster-api/cluster-api-provider-outscale output
      placeholder: cluster-api/cluster-api-provider-outscale logs that will help us to understand what happened
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: |
        example:
          - **Kubernetes version: (use `kubectl version`)**: v1.23.6
          - **OS (e.g. from `/etc/os-release`)**: CentOS Linux 7 (Core)
          - **Kernel (e.g. `uname -a`)**: 3.10.0-1160.15.2.el7.x86_64
          - **cluster-api-provider-outscale version**: v1.1.3
          - **cluster-api version**: v0.1.0
          - **Install tools**: calico, ...
          - **Kubernetes Distribution**: rke
          - **Kubernetes Distribution Version**:  v1.3.10
      value: "- Kubernetes version: (use `kubectl version`): \n- OS (e.g. from `/etc/os-release`):\n- Kernel (e.g. `uname -a`):\n- cluster-api-provider-outscale version:\n- cluster-api version: \n- Install tools:\n- Kubernetes Distribution:\n- Kubernetes Diestribution version: \n"
      render: markdown
    validations:
      required: true
