name: Feature Enhancement Request
description: Suggest a new feature or improvement for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: What is the current limitation or issue this feature would solve?
      placeholder: |
        Example: Currently, there is no way to simulate resource creation without applying it. A dry-run mode would help test configurations safely.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or enhancement you’d like to see implemented.
      placeholder: |
        Example: Add a `--dry-run` flag to the `capoctl apply` command that validates input and shows the diff without making changes.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, alternatives considered, or related feature requests.
      placeholder: Include any links, config examples, or screenshots that support your proposal.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide your environment context to help us understand compatibility or constraints.
      value: |
        - Kubernetes version (`kubectl version`):
        - OS (`/etc/os-release`):
        - Kernel (`uname -a`):
        - cluster-api-provider-outscale version:
        - cluster-api version:
        - Install tools:
        - Kubernetes distribution:
        - Kubernetes distribution version:
      render: markdown
    validations:
      required: true
