name: Feature enhancement request
description: Request a feature for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - outscale-vbr
body:
  - type: textarea
    id: explain
    attributes:
      label: Explain problem to solve
      description: Which problem your feature request will solve ?
      placeholder: Explain with a clear and concise description
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the solution you would like
      description: Describe with a clear and concise description
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any context about your feature request that will allow us to understand your feature request
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: |
        example:
          - **Kubernetes version: (use `kubectl version`)**: v1.23.6
          - **OS (e.g. from `/etc/os-release`)**: CentOS Linux 7 (Core)
          - **Kernel (e.g. `uname -a`)**: 3.10.0-1160.15.2.el7.x86_64
          - **cluster-api-provider-outscale version**: v1.1.3
          - **cluster-api version**: v0.1.0
          - **Install tools**: calico, ...
          - **Kubernetes Distribution**: rke
          - **Kubernetes Distribution Version**:  v1.3.10
      value: |
        - Kubernetes version: (use `kubectl version`):
        - OS (e.g. from `/etc/os-release`):
        - Kernel (e.g. `uname -a`):
        - cluster-api-provider-outscale version:
        - cluster-api version:
        - Install tools:
        - Kubernetes Distribution:
        - Kubernetes Diestribution version:
      render: markdown
    validations:
      required: true
