//go:build !ignore_autogenerated_core_v1beta1
// +build !ignore_autogenerated_core_v1beta1

/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1beta2 "github.com/outscale-dev/cluster-api-provider-outscale.git/api/v1beta2"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*OscCluster)(nil), (*v1beta2.OscCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscCluster_To_v1beta2_OscCluster(a.(*OscCluster), b.(*v1beta2.OscCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscCluster)(nil), (*OscCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscCluster_To_v1beta1_OscCluster(a.(*v1beta2.OscCluster), b.(*OscCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscClusterList)(nil), (*v1beta2.OscClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscClusterList_To_v1beta2_OscClusterList(a.(*OscClusterList), b.(*v1beta2.OscClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscClusterList)(nil), (*OscClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscClusterList_To_v1beta1_OscClusterList(a.(*v1beta2.OscClusterList), b.(*OscClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscClusterSpec)(nil), (*v1beta2.OscClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscClusterSpec_To_v1beta2_OscClusterSpec(a.(*OscClusterSpec), b.(*v1beta2.OscClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscClusterSpec)(nil), (*OscClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscClusterSpec_To_v1beta1_OscClusterSpec(a.(*v1beta2.OscClusterSpec), b.(*OscClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscClusterStatus)(nil), (*v1beta2.OscClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscClusterStatus_To_v1beta2_OscClusterStatus(a.(*OscClusterStatus), b.(*v1beta2.OscClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscClusterTemplate)(nil), (*v1beta2.OscClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscClusterTemplate_To_v1beta2_OscClusterTemplate(a.(*OscClusterTemplate), b.(*v1beta2.OscClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscClusterTemplate)(nil), (*OscClusterTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscClusterTemplate_To_v1beta1_OscClusterTemplate(a.(*v1beta2.OscClusterTemplate), b.(*OscClusterTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscClusterTemplateList)(nil), (*v1beta2.OscClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscClusterTemplateList_To_v1beta2_OscClusterTemplateList(a.(*OscClusterTemplateList), b.(*v1beta2.OscClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscClusterTemplateList)(nil), (*OscClusterTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscClusterTemplateList_To_v1beta1_OscClusterTemplateList(a.(*v1beta2.OscClusterTemplateList), b.(*OscClusterTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscClusterTemplateResource)(nil), (*v1beta2.OscClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscClusterTemplateResource_To_v1beta2_OscClusterTemplateResource(a.(*OscClusterTemplateResource), b.(*v1beta2.OscClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscClusterTemplateResource)(nil), (*OscClusterTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscClusterTemplateResource_To_v1beta1_OscClusterTemplateResource(a.(*v1beta2.OscClusterTemplateResource), b.(*OscClusterTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscClusterTemplateSpec)(nil), (*v1beta2.OscClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscClusterTemplateSpec_To_v1beta2_OscClusterTemplateSpec(a.(*OscClusterTemplateSpec), b.(*v1beta2.OscClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscClusterTemplateSpec)(nil), (*OscClusterTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscClusterTemplateSpec_To_v1beta1_OscClusterTemplateSpec(a.(*v1beta2.OscClusterTemplateSpec), b.(*OscClusterTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscImage)(nil), (*v1beta2.OscImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscImage_To_v1beta2_OscImage(a.(*OscImage), b.(*v1beta2.OscImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscImage)(nil), (*OscImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscImage_To_v1beta1_OscImage(a.(*v1beta2.OscImage), b.(*OscImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscInternetService)(nil), (*v1beta2.OscInternetService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscInternetService_To_v1beta2_OscInternetService(a.(*OscInternetService), b.(*v1beta2.OscInternetService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscInternetService)(nil), (*OscInternetService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscInternetService_To_v1beta1_OscInternetService(a.(*v1beta2.OscInternetService), b.(*OscInternetService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscKeypair)(nil), (*v1beta2.OscKeypair)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscKeypair_To_v1beta2_OscKeypair(a.(*OscKeypair), b.(*v1beta2.OscKeypair), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscKeypair)(nil), (*OscKeypair)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscKeypair_To_v1beta1_OscKeypair(a.(*v1beta2.OscKeypair), b.(*OscKeypair), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscLoadBalancer)(nil), (*v1beta2.OscLoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscLoadBalancer_To_v1beta2_OscLoadBalancer(a.(*OscLoadBalancer), b.(*v1beta2.OscLoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscLoadBalancer)(nil), (*OscLoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscLoadBalancer_To_v1beta1_OscLoadBalancer(a.(*v1beta2.OscLoadBalancer), b.(*OscLoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscLoadBalancerHealthCheck)(nil), (*v1beta2.OscLoadBalancerHealthCheck)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscLoadBalancerHealthCheck_To_v1beta2_OscLoadBalancerHealthCheck(a.(*OscLoadBalancerHealthCheck), b.(*v1beta2.OscLoadBalancerHealthCheck), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscLoadBalancerHealthCheck)(nil), (*OscLoadBalancerHealthCheck)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscLoadBalancerHealthCheck_To_v1beta1_OscLoadBalancerHealthCheck(a.(*v1beta2.OscLoadBalancerHealthCheck), b.(*OscLoadBalancerHealthCheck), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscLoadBalancerListener)(nil), (*v1beta2.OscLoadBalancerListener)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscLoadBalancerListener_To_v1beta2_OscLoadBalancerListener(a.(*OscLoadBalancerListener), b.(*v1beta2.OscLoadBalancerListener), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscLoadBalancerListener)(nil), (*OscLoadBalancerListener)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscLoadBalancerListener_To_v1beta1_OscLoadBalancerListener(a.(*v1beta2.OscLoadBalancerListener), b.(*OscLoadBalancerListener), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachine)(nil), (*v1beta2.OscMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachine_To_v1beta2_OscMachine(a.(*OscMachine), b.(*v1beta2.OscMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachine)(nil), (*OscMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachine_To_v1beta1_OscMachine(a.(*v1beta2.OscMachine), b.(*OscMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineList)(nil), (*v1beta2.OscMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineList_To_v1beta2_OscMachineList(a.(*OscMachineList), b.(*v1beta2.OscMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineList)(nil), (*OscMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineList_To_v1beta1_OscMachineList(a.(*v1beta2.OscMachineList), b.(*OscMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineSpec)(nil), (*v1beta2.OscMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineSpec_To_v1beta2_OscMachineSpec(a.(*OscMachineSpec), b.(*v1beta2.OscMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineSpec)(nil), (*OscMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineSpec_To_v1beta1_OscMachineSpec(a.(*v1beta2.OscMachineSpec), b.(*OscMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineStatus)(nil), (*v1beta2.OscMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineStatus_To_v1beta2_OscMachineStatus(a.(*OscMachineStatus), b.(*v1beta2.OscMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineStatus)(nil), (*OscMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineStatus_To_v1beta1_OscMachineStatus(a.(*v1beta2.OscMachineStatus), b.(*OscMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineTemplate)(nil), (*v1beta2.OscMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineTemplate_To_v1beta2_OscMachineTemplate(a.(*OscMachineTemplate), b.(*v1beta2.OscMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineTemplate)(nil), (*OscMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineTemplate_To_v1beta1_OscMachineTemplate(a.(*v1beta2.OscMachineTemplate), b.(*OscMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineTemplateList)(nil), (*v1beta2.OscMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineTemplateList_To_v1beta2_OscMachineTemplateList(a.(*OscMachineTemplateList), b.(*v1beta2.OscMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineTemplateList)(nil), (*OscMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineTemplateList_To_v1beta1_OscMachineTemplateList(a.(*v1beta2.OscMachineTemplateList), b.(*OscMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineTemplateResource)(nil), (*v1beta2.OscMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineTemplateResource_To_v1beta2_OscMachineTemplateResource(a.(*OscMachineTemplateResource), b.(*v1beta2.OscMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineTemplateResource)(nil), (*OscMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineTemplateResource_To_v1beta1_OscMachineTemplateResource(a.(*v1beta2.OscMachineTemplateResource), b.(*OscMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineTemplateSpec)(nil), (*v1beta2.OscMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineTemplateSpec_To_v1beta2_OscMachineTemplateSpec(a.(*OscMachineTemplateSpec), b.(*v1beta2.OscMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineTemplateSpec)(nil), (*OscMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineTemplateSpec_To_v1beta1_OscMachineTemplateSpec(a.(*v1beta2.OscMachineTemplateSpec), b.(*OscMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscMachineTemplateStatus)(nil), (*v1beta2.OscMachineTemplateStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscMachineTemplateStatus_To_v1beta2_OscMachineTemplateStatus(a.(*OscMachineTemplateStatus), b.(*v1beta2.OscMachineTemplateStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscMachineTemplateStatus)(nil), (*OscMachineTemplateStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscMachineTemplateStatus_To_v1beta1_OscMachineTemplateStatus(a.(*v1beta2.OscMachineTemplateStatus), b.(*OscMachineTemplateStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscNatService)(nil), (*v1beta2.OscNatService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscNatService_To_v1beta2_OscNatService(a.(*OscNatService), b.(*v1beta2.OscNatService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscNatService)(nil), (*OscNatService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscNatService_To_v1beta1_OscNatService(a.(*v1beta2.OscNatService), b.(*OscNatService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscNet)(nil), (*v1beta2.OscNet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscNet_To_v1beta2_OscNet(a.(*OscNet), b.(*v1beta2.OscNet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscNet)(nil), (*OscNet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscNet_To_v1beta1_OscNet(a.(*v1beta2.OscNet), b.(*OscNet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscNetwork)(nil), (*v1beta2.OscNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscNetwork_To_v1beta2_OscNetwork(a.(*OscNetwork), b.(*v1beta2.OscNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscNode)(nil), (*v1beta2.OscNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscNode_To_v1beta2_OscNode(a.(*OscNode), b.(*v1beta2.OscNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscNode)(nil), (*OscNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscNode_To_v1beta1_OscNode(a.(*v1beta2.OscNode), b.(*OscNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscNodeResource)(nil), (*v1beta2.OscNodeResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscNodeResource_To_v1beta2_OscNodeResource(a.(*OscNodeResource), b.(*v1beta2.OscNodeResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscNodeResource)(nil), (*OscNodeResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscNodeResource_To_v1beta1_OscNodeResource(a.(*v1beta2.OscNodeResource), b.(*OscNodeResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscPrivateIpElement)(nil), (*v1beta2.OscPrivateIpElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscPrivateIpElement_To_v1beta2_OscPrivateIpElement(a.(*OscPrivateIpElement), b.(*v1beta2.OscPrivateIpElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscPrivateIpElement)(nil), (*OscPrivateIpElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscPrivateIpElement_To_v1beta1_OscPrivateIpElement(a.(*v1beta2.OscPrivateIpElement), b.(*OscPrivateIpElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscPublicIp)(nil), (*v1beta2.OscPublicIp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscPublicIp_To_v1beta2_OscPublicIp(a.(*OscPublicIp), b.(*v1beta2.OscPublicIp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscPublicIp)(nil), (*OscPublicIp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscPublicIp_To_v1beta1_OscPublicIp(a.(*v1beta2.OscPublicIp), b.(*OscPublicIp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscRootDisk)(nil), (*v1beta2.OscRootDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscRootDisk_To_v1beta2_OscRootDisk(a.(*OscRootDisk), b.(*v1beta2.OscRootDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscRootDisk)(nil), (*OscRootDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscRootDisk_To_v1beta1_OscRootDisk(a.(*v1beta2.OscRootDisk), b.(*OscRootDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscRoute)(nil), (*v1beta2.OscRoute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscRoute_To_v1beta2_OscRoute(a.(*OscRoute), b.(*v1beta2.OscRoute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscRoute)(nil), (*OscRoute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscRoute_To_v1beta1_OscRoute(a.(*v1beta2.OscRoute), b.(*OscRoute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscSecurityGroup)(nil), (*v1beta2.OscSecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscSecurityGroup_To_v1beta2_OscSecurityGroup(a.(*OscSecurityGroup), b.(*v1beta2.OscSecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscSecurityGroup)(nil), (*OscSecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscSecurityGroup_To_v1beta1_OscSecurityGroup(a.(*v1beta2.OscSecurityGroup), b.(*OscSecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscSecurityGroupElement)(nil), (*v1beta2.OscSecurityGroupElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscSecurityGroupElement_To_v1beta2_OscSecurityGroupElement(a.(*OscSecurityGroupElement), b.(*v1beta2.OscSecurityGroupElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscSecurityGroupElement)(nil), (*OscSecurityGroupElement)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscSecurityGroupElement_To_v1beta1_OscSecurityGroupElement(a.(*v1beta2.OscSecurityGroupElement), b.(*OscSecurityGroupElement), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscSecurityGroupRule)(nil), (*v1beta2.OscSecurityGroupRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscSecurityGroupRule_To_v1beta2_OscSecurityGroupRule(a.(*OscSecurityGroupRule), b.(*v1beta2.OscSecurityGroupRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscSecurityGroupRule)(nil), (*OscSecurityGroupRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscSecurityGroupRule_To_v1beta1_OscSecurityGroupRule(a.(*v1beta2.OscSecurityGroupRule), b.(*OscSecurityGroupRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscSubnet)(nil), (*v1beta2.OscSubnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscSubnet_To_v1beta2_OscSubnet(a.(*OscSubnet), b.(*v1beta2.OscSubnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscSubnet)(nil), (*OscSubnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscSubnet_To_v1beta1_OscSubnet(a.(*v1beta2.OscSubnet), b.(*OscSubnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscVm)(nil), (*v1beta2.OscVm)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscVm_To_v1beta2_OscVm(a.(*OscVm), b.(*v1beta2.OscVm), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscVm)(nil), (*OscVm)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscVm_To_v1beta1_OscVm(a.(*v1beta2.OscVm), b.(*OscVm), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OscVolume)(nil), (*v1beta2.OscVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscVolume_To_v1beta2_OscVolume(a.(*OscVolume), b.(*v1beta2.OscVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.OscVolume)(nil), (*OscVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscVolume_To_v1beta1_OscVolume(a.(*v1beta2.OscVolume), b.(*OscVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*OscNetworkResource)(nil), (*v1beta2.OscNetworkResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscNetworkResource_To_v1beta2_OscNetworkResource(a.(*OscNetworkResource), b.(*v1beta2.OscNetworkResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*OscResourceMapReference)(nil), (*v1beta2.OscResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(a.(*OscResourceMapReference), b.(*v1beta2.OscResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*OscRouteTable)(nil), (*v1beta2.OscRouteTable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OscRouteTable_To_v1beta2_OscRouteTable(a.(*OscRouteTable), b.(*v1beta2.OscRouteTable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.OscClusterStatus)(nil), (*OscClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscClusterStatus_To_v1beta1_OscClusterStatus(a.(*v1beta2.OscClusterStatus), b.(*OscClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.OscNetworkResource)(nil), (*OscNetworkResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscNetworkResource_To_v1beta1_OscNetworkResource(a.(*v1beta2.OscNetworkResource), b.(*OscNetworkResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.OscNetwork)(nil), (*OscNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscNetwork_To_v1beta1_OscNetwork(a.(*v1beta2.OscNetwork), b.(*OscNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.OscResourceReference)(nil), (*OscResourceMapReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(a.(*v1beta2.OscResourceReference), b.(*OscResourceMapReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.OscRouteTable)(nil), (*OscRouteTable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OscRouteTable_To_v1beta1_OscRouteTable(a.(*v1beta2.OscRouteTable), b.(*OscRouteTable), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_OscCluster_To_v1beta2_OscCluster(in *OscCluster, out *v1beta2.OscCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OscClusterSpec_To_v1beta2_OscClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscClusterStatus_To_v1beta2_OscClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscCluster_To_v1beta2_OscCluster is an autogenerated conversion function.
func Convert_v1beta1_OscCluster_To_v1beta2_OscCluster(in *OscCluster, out *v1beta2.OscCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_OscCluster_To_v1beta2_OscCluster(in, out, s)
}

func autoConvert_v1beta2_OscCluster_To_v1beta1_OscCluster(in *v1beta2.OscCluster, out *OscCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OscClusterSpec_To_v1beta1_OscClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscClusterStatus_To_v1beta1_OscClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscCluster_To_v1beta1_OscCluster is an autogenerated conversion function.
func Convert_v1beta2_OscCluster_To_v1beta1_OscCluster(in *v1beta2.OscCluster, out *OscCluster, s conversion.Scope) error {
	return autoConvert_v1beta2_OscCluster_To_v1beta1_OscCluster(in, out, s)
}

func autoConvert_v1beta1_OscClusterList_To_v1beta2_OscClusterList(in *OscClusterList, out *v1beta2.OscClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.OscCluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_OscCluster_To_v1beta2_OscCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_OscClusterList_To_v1beta2_OscClusterList is an autogenerated conversion function.
func Convert_v1beta1_OscClusterList_To_v1beta2_OscClusterList(in *OscClusterList, out *v1beta2.OscClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_OscClusterList_To_v1beta2_OscClusterList(in, out, s)
}

func autoConvert_v1beta2_OscClusterList_To_v1beta1_OscClusterList(in *v1beta2.OscClusterList, out *OscClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OscCluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_OscCluster_To_v1beta1_OscCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_OscClusterList_To_v1beta1_OscClusterList is an autogenerated conversion function.
func Convert_v1beta2_OscClusterList_To_v1beta1_OscClusterList(in *v1beta2.OscClusterList, out *OscClusterList, s conversion.Scope) error {
	return autoConvert_v1beta2_OscClusterList_To_v1beta1_OscClusterList(in, out, s)
}

func autoConvert_v1beta1_OscClusterSpec_To_v1beta2_OscClusterSpec(in *OscClusterSpec, out *v1beta2.OscClusterSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_OscNetwork_To_v1beta2_OscNetwork(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	return nil
}

// Convert_v1beta1_OscClusterSpec_To_v1beta2_OscClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_OscClusterSpec_To_v1beta2_OscClusterSpec(in *OscClusterSpec, out *v1beta2.OscClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_OscClusterSpec_To_v1beta2_OscClusterSpec(in, out, s)
}

func autoConvert_v1beta2_OscClusterSpec_To_v1beta1_OscClusterSpec(in *v1beta2.OscClusterSpec, out *OscClusterSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_OscNetwork_To_v1beta1_OscNetwork(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	return nil
}

// Convert_v1beta2_OscClusterSpec_To_v1beta1_OscClusterSpec is an autogenerated conversion function.
func Convert_v1beta2_OscClusterSpec_To_v1beta1_OscClusterSpec(in *v1beta2.OscClusterSpec, out *OscClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_OscClusterSpec_To_v1beta1_OscClusterSpec(in, out, s)
}

func autoConvert_v1beta1_OscClusterStatus_To_v1beta2_OscClusterStatus(in *OscClusterStatus, out *v1beta2.OscClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	if err := Convert_v1beta1_OscNetworkResource_To_v1beta2_OscNetworkResource(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_OscClusterStatus_To_v1beta2_OscClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_OscClusterStatus_To_v1beta2_OscClusterStatus(in *OscClusterStatus, out *v1beta2.OscClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_OscClusterStatus_To_v1beta2_OscClusterStatus(in, out, s)
}

func autoConvert_v1beta2_OscClusterStatus_To_v1beta1_OscClusterStatus(in *v1beta2.OscClusterStatus, out *OscClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	if err := Convert_v1beta2_OscNetworkResource_To_v1beta1_OscNetworkResource(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	// WARNING: in.VmState requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_OscClusterTemplate_To_v1beta2_OscClusterTemplate(in *OscClusterTemplate, out *v1beta2.OscClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OscClusterTemplateSpec_To_v1beta2_OscClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscClusterTemplate_To_v1beta2_OscClusterTemplate is an autogenerated conversion function.
func Convert_v1beta1_OscClusterTemplate_To_v1beta2_OscClusterTemplate(in *OscClusterTemplate, out *v1beta2.OscClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_OscClusterTemplate_To_v1beta2_OscClusterTemplate(in, out, s)
}

func autoConvert_v1beta2_OscClusterTemplate_To_v1beta1_OscClusterTemplate(in *v1beta2.OscClusterTemplate, out *OscClusterTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OscClusterTemplateSpec_To_v1beta1_OscClusterTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscClusterTemplate_To_v1beta1_OscClusterTemplate is an autogenerated conversion function.
func Convert_v1beta2_OscClusterTemplate_To_v1beta1_OscClusterTemplate(in *v1beta2.OscClusterTemplate, out *OscClusterTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_OscClusterTemplate_To_v1beta1_OscClusterTemplate(in, out, s)
}

func autoConvert_v1beta1_OscClusterTemplateList_To_v1beta2_OscClusterTemplateList(in *OscClusterTemplateList, out *v1beta2.OscClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.OscClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_OscClusterTemplate_To_v1beta2_OscClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_OscClusterTemplateList_To_v1beta2_OscClusterTemplateList is an autogenerated conversion function.
func Convert_v1beta1_OscClusterTemplateList_To_v1beta2_OscClusterTemplateList(in *OscClusterTemplateList, out *v1beta2.OscClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_OscClusterTemplateList_To_v1beta2_OscClusterTemplateList(in, out, s)
}

func autoConvert_v1beta2_OscClusterTemplateList_To_v1beta1_OscClusterTemplateList(in *v1beta2.OscClusterTemplateList, out *OscClusterTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OscClusterTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_OscClusterTemplate_To_v1beta1_OscClusterTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_OscClusterTemplateList_To_v1beta1_OscClusterTemplateList is an autogenerated conversion function.
func Convert_v1beta2_OscClusterTemplateList_To_v1beta1_OscClusterTemplateList(in *v1beta2.OscClusterTemplateList, out *OscClusterTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_OscClusterTemplateList_To_v1beta1_OscClusterTemplateList(in, out, s)
}

func autoConvert_v1beta1_OscClusterTemplateResource_To_v1beta2_OscClusterTemplateResource(in *OscClusterTemplateResource, out *v1beta2.OscClusterTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OscClusterSpec_To_v1beta2_OscClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscClusterTemplateResource_To_v1beta2_OscClusterTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_OscClusterTemplateResource_To_v1beta2_OscClusterTemplateResource(in *OscClusterTemplateResource, out *v1beta2.OscClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_OscClusterTemplateResource_To_v1beta2_OscClusterTemplateResource(in, out, s)
}

func autoConvert_v1beta2_OscClusterTemplateResource_To_v1beta1_OscClusterTemplateResource(in *v1beta2.OscClusterTemplateResource, out *OscClusterTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OscClusterSpec_To_v1beta1_OscClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscClusterTemplateResource_To_v1beta1_OscClusterTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_OscClusterTemplateResource_To_v1beta1_OscClusterTemplateResource(in *v1beta2.OscClusterTemplateResource, out *OscClusterTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_OscClusterTemplateResource_To_v1beta1_OscClusterTemplateResource(in, out, s)
}

func autoConvert_v1beta1_OscClusterTemplateSpec_To_v1beta2_OscClusterTemplateSpec(in *OscClusterTemplateSpec, out *v1beta2.OscClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_OscClusterTemplateResource_To_v1beta2_OscClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscClusterTemplateSpec_To_v1beta2_OscClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_OscClusterTemplateSpec_To_v1beta2_OscClusterTemplateSpec(in *OscClusterTemplateSpec, out *v1beta2.OscClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_OscClusterTemplateSpec_To_v1beta2_OscClusterTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_OscClusterTemplateSpec_To_v1beta1_OscClusterTemplateSpec(in *v1beta2.OscClusterTemplateSpec, out *OscClusterTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_OscClusterTemplateResource_To_v1beta1_OscClusterTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscClusterTemplateSpec_To_v1beta1_OscClusterTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_OscClusterTemplateSpec_To_v1beta1_OscClusterTemplateSpec(in *v1beta2.OscClusterTemplateSpec, out *OscClusterTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_OscClusterTemplateSpec_To_v1beta1_OscClusterTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_OscImage_To_v1beta2_OscImage(in *OscImage, out *v1beta2.OscImage, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscImage_To_v1beta2_OscImage is an autogenerated conversion function.
func Convert_v1beta1_OscImage_To_v1beta2_OscImage(in *OscImage, out *v1beta2.OscImage, s conversion.Scope) error {
	return autoConvert_v1beta1_OscImage_To_v1beta2_OscImage(in, out, s)
}

func autoConvert_v1beta2_OscImage_To_v1beta1_OscImage(in *v1beta2.OscImage, out *OscImage, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscImage_To_v1beta1_OscImage is an autogenerated conversion function.
func Convert_v1beta2_OscImage_To_v1beta1_OscImage(in *v1beta2.OscImage, out *OscImage, s conversion.Scope) error {
	return autoConvert_v1beta2_OscImage_To_v1beta1_OscImage(in, out, s)
}

func autoConvert_v1beta1_OscInternetService_To_v1beta2_OscInternetService(in *OscInternetService, out *v1beta2.OscInternetService, s conversion.Scope) error {
	out.Name = in.Name
	out.ClusterName = in.ClusterName
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscInternetService_To_v1beta2_OscInternetService is an autogenerated conversion function.
func Convert_v1beta1_OscInternetService_To_v1beta2_OscInternetService(in *OscInternetService, out *v1beta2.OscInternetService, s conversion.Scope) error {
	return autoConvert_v1beta1_OscInternetService_To_v1beta2_OscInternetService(in, out, s)
}

func autoConvert_v1beta2_OscInternetService_To_v1beta1_OscInternetService(in *v1beta2.OscInternetService, out *OscInternetService, s conversion.Scope) error {
	out.Name = in.Name
	out.ClusterName = in.ClusterName
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscInternetService_To_v1beta1_OscInternetService is an autogenerated conversion function.
func Convert_v1beta2_OscInternetService_To_v1beta1_OscInternetService(in *v1beta2.OscInternetService, out *OscInternetService, s conversion.Scope) error {
	return autoConvert_v1beta2_OscInternetService_To_v1beta1_OscInternetService(in, out, s)
}

func autoConvert_v1beta1_OscKeypair_To_v1beta2_OscKeypair(in *OscKeypair, out *v1beta2.OscKeypair, s conversion.Scope) error {
	out.Name = in.Name
	out.PublicKey = in.PublicKey
	out.ResourceId = in.ResourceId
	out.ClusterName = in.ClusterName
	out.DeleteKeypair = in.DeleteKeypair
	return nil
}

// Convert_v1beta1_OscKeypair_To_v1beta2_OscKeypair is an autogenerated conversion function.
func Convert_v1beta1_OscKeypair_To_v1beta2_OscKeypair(in *OscKeypair, out *v1beta2.OscKeypair, s conversion.Scope) error {
	return autoConvert_v1beta1_OscKeypair_To_v1beta2_OscKeypair(in, out, s)
}

func autoConvert_v1beta2_OscKeypair_To_v1beta1_OscKeypair(in *v1beta2.OscKeypair, out *OscKeypair, s conversion.Scope) error {
	out.Name = in.Name
	out.PublicKey = in.PublicKey
	out.ResourceId = in.ResourceId
	out.ClusterName = in.ClusterName
	out.DeleteKeypair = in.DeleteKeypair
	return nil
}

// Convert_v1beta2_OscKeypair_To_v1beta1_OscKeypair is an autogenerated conversion function.
func Convert_v1beta2_OscKeypair_To_v1beta1_OscKeypair(in *v1beta2.OscKeypair, out *OscKeypair, s conversion.Scope) error {
	return autoConvert_v1beta2_OscKeypair_To_v1beta1_OscKeypair(in, out, s)
}

func autoConvert_v1beta1_OscLoadBalancer_To_v1beta2_OscLoadBalancer(in *OscLoadBalancer, out *v1beta2.OscLoadBalancer, s conversion.Scope) error {
	out.LoadBalancerName = in.LoadBalancerName
	out.LoadBalancerType = in.LoadBalancerType
	out.SubnetName = in.SubnetName
	out.SecurityGroupName = in.SecurityGroupName
	if err := Convert_v1beta1_OscLoadBalancerListener_To_v1beta2_OscLoadBalancerListener(&in.Listener, &out.Listener, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscLoadBalancerHealthCheck_To_v1beta2_OscLoadBalancerHealthCheck(&in.HealthCheck, &out.HealthCheck, s); err != nil {
		return err
	}
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1beta1_OscLoadBalancer_To_v1beta2_OscLoadBalancer is an autogenerated conversion function.
func Convert_v1beta1_OscLoadBalancer_To_v1beta2_OscLoadBalancer(in *OscLoadBalancer, out *v1beta2.OscLoadBalancer, s conversion.Scope) error {
	return autoConvert_v1beta1_OscLoadBalancer_To_v1beta2_OscLoadBalancer(in, out, s)
}

func autoConvert_v1beta2_OscLoadBalancer_To_v1beta1_OscLoadBalancer(in *v1beta2.OscLoadBalancer, out *OscLoadBalancer, s conversion.Scope) error {
	out.LoadBalancerName = in.LoadBalancerName
	out.LoadBalancerType = in.LoadBalancerType
	out.SubnetName = in.SubnetName
	out.SecurityGroupName = in.SecurityGroupName
	if err := Convert_v1beta2_OscLoadBalancerListener_To_v1beta1_OscLoadBalancerListener(&in.Listener, &out.Listener, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscLoadBalancerHealthCheck_To_v1beta1_OscLoadBalancerHealthCheck(&in.HealthCheck, &out.HealthCheck, s); err != nil {
		return err
	}
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1beta2_OscLoadBalancer_To_v1beta1_OscLoadBalancer is an autogenerated conversion function.
func Convert_v1beta2_OscLoadBalancer_To_v1beta1_OscLoadBalancer(in *v1beta2.OscLoadBalancer, out *OscLoadBalancer, s conversion.Scope) error {
	return autoConvert_v1beta2_OscLoadBalancer_To_v1beta1_OscLoadBalancer(in, out, s)
}

func autoConvert_v1beta1_OscLoadBalancerHealthCheck_To_v1beta2_OscLoadBalancerHealthCheck(in *OscLoadBalancerHealthCheck, out *v1beta2.OscLoadBalancerHealthCheck, s conversion.Scope) error {
	out.CheckInterval = in.CheckInterval
	out.HealthyThreshold = in.HealthyThreshold
	out.Port = in.Port
	out.Protocol = in.Protocol
	out.Timeout = in.Timeout
	out.UnhealthyThreshold = in.UnhealthyThreshold
	return nil
}

// Convert_v1beta1_OscLoadBalancerHealthCheck_To_v1beta2_OscLoadBalancerHealthCheck is an autogenerated conversion function.
func Convert_v1beta1_OscLoadBalancerHealthCheck_To_v1beta2_OscLoadBalancerHealthCheck(in *OscLoadBalancerHealthCheck, out *v1beta2.OscLoadBalancerHealthCheck, s conversion.Scope) error {
	return autoConvert_v1beta1_OscLoadBalancerHealthCheck_To_v1beta2_OscLoadBalancerHealthCheck(in, out, s)
}

func autoConvert_v1beta2_OscLoadBalancerHealthCheck_To_v1beta1_OscLoadBalancerHealthCheck(in *v1beta2.OscLoadBalancerHealthCheck, out *OscLoadBalancerHealthCheck, s conversion.Scope) error {
	out.CheckInterval = in.CheckInterval
	out.HealthyThreshold = in.HealthyThreshold
	out.Port = in.Port
	out.Protocol = in.Protocol
	out.Timeout = in.Timeout
	out.UnhealthyThreshold = in.UnhealthyThreshold
	return nil
}

// Convert_v1beta2_OscLoadBalancerHealthCheck_To_v1beta1_OscLoadBalancerHealthCheck is an autogenerated conversion function.
func Convert_v1beta2_OscLoadBalancerHealthCheck_To_v1beta1_OscLoadBalancerHealthCheck(in *v1beta2.OscLoadBalancerHealthCheck, out *OscLoadBalancerHealthCheck, s conversion.Scope) error {
	return autoConvert_v1beta2_OscLoadBalancerHealthCheck_To_v1beta1_OscLoadBalancerHealthCheck(in, out, s)
}

func autoConvert_v1beta1_OscLoadBalancerListener_To_v1beta2_OscLoadBalancerListener(in *OscLoadBalancerListener, out *v1beta2.OscLoadBalancerListener, s conversion.Scope) error {
	out.BackendPort = in.BackendPort
	out.BackendProtocol = in.BackendProtocol
	out.LoadBalancerPort = in.LoadBalancerPort
	out.LoadBalancerProtocol = in.LoadBalancerProtocol
	return nil
}

// Convert_v1beta1_OscLoadBalancerListener_To_v1beta2_OscLoadBalancerListener is an autogenerated conversion function.
func Convert_v1beta1_OscLoadBalancerListener_To_v1beta2_OscLoadBalancerListener(in *OscLoadBalancerListener, out *v1beta2.OscLoadBalancerListener, s conversion.Scope) error {
	return autoConvert_v1beta1_OscLoadBalancerListener_To_v1beta2_OscLoadBalancerListener(in, out, s)
}

func autoConvert_v1beta2_OscLoadBalancerListener_To_v1beta1_OscLoadBalancerListener(in *v1beta2.OscLoadBalancerListener, out *OscLoadBalancerListener, s conversion.Scope) error {
	out.BackendPort = in.BackendPort
	out.BackendProtocol = in.BackendProtocol
	out.LoadBalancerPort = in.LoadBalancerPort
	out.LoadBalancerProtocol = in.LoadBalancerProtocol
	return nil
}

// Convert_v1beta2_OscLoadBalancerListener_To_v1beta1_OscLoadBalancerListener is an autogenerated conversion function.
func Convert_v1beta2_OscLoadBalancerListener_To_v1beta1_OscLoadBalancerListener(in *v1beta2.OscLoadBalancerListener, out *OscLoadBalancerListener, s conversion.Scope) error {
	return autoConvert_v1beta2_OscLoadBalancerListener_To_v1beta1_OscLoadBalancerListener(in, out, s)
}

func autoConvert_v1beta1_OscMachine_To_v1beta2_OscMachine(in *OscMachine, out *v1beta2.OscMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OscMachineSpec_To_v1beta2_OscMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscMachineStatus_To_v1beta2_OscMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscMachine_To_v1beta2_OscMachine is an autogenerated conversion function.
func Convert_v1beta1_OscMachine_To_v1beta2_OscMachine(in *OscMachine, out *v1beta2.OscMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachine_To_v1beta2_OscMachine(in, out, s)
}

func autoConvert_v1beta2_OscMachine_To_v1beta1_OscMachine(in *v1beta2.OscMachine, out *OscMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OscMachineSpec_To_v1beta1_OscMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscMachineStatus_To_v1beta1_OscMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscMachine_To_v1beta1_OscMachine is an autogenerated conversion function.
func Convert_v1beta2_OscMachine_To_v1beta1_OscMachine(in *v1beta2.OscMachine, out *OscMachine, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachine_To_v1beta1_OscMachine(in, out, s)
}

func autoConvert_v1beta1_OscMachineList_To_v1beta2_OscMachineList(in *OscMachineList, out *v1beta2.OscMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.OscMachine, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_OscMachine_To_v1beta2_OscMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_OscMachineList_To_v1beta2_OscMachineList is an autogenerated conversion function.
func Convert_v1beta1_OscMachineList_To_v1beta2_OscMachineList(in *OscMachineList, out *v1beta2.OscMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineList_To_v1beta2_OscMachineList(in, out, s)
}

func autoConvert_v1beta2_OscMachineList_To_v1beta1_OscMachineList(in *v1beta2.OscMachineList, out *OscMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OscMachine, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_OscMachine_To_v1beta1_OscMachine(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_OscMachineList_To_v1beta1_OscMachineList is an autogenerated conversion function.
func Convert_v1beta2_OscMachineList_To_v1beta1_OscMachineList(in *v1beta2.OscMachineList, out *OscMachineList, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineList_To_v1beta1_OscMachineList(in, out, s)
}

func autoConvert_v1beta1_OscMachineSpec_To_v1beta2_OscMachineSpec(in *OscMachineSpec, out *v1beta2.OscMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1beta1_OscNode_To_v1beta2_OscNode(&in.Node, &out.Node, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscMachineSpec_To_v1beta2_OscMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_OscMachineSpec_To_v1beta2_OscMachineSpec(in *OscMachineSpec, out *v1beta2.OscMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineSpec_To_v1beta2_OscMachineSpec(in, out, s)
}

func autoConvert_v1beta2_OscMachineSpec_To_v1beta1_OscMachineSpec(in *v1beta2.OscMachineSpec, out *OscMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1beta2_OscNode_To_v1beta1_OscNode(&in.Node, &out.Node, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscMachineSpec_To_v1beta1_OscMachineSpec is an autogenerated conversion function.
func Convert_v1beta2_OscMachineSpec_To_v1beta1_OscMachineSpec(in *v1beta2.OscMachineSpec, out *OscMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineSpec_To_v1beta1_OscMachineSpec(in, out, s)
}

// Convert_v1beta1_OscMachineStatus_To_v1beta2_OscMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_OscMachineStatus_To_v1beta2_OscMachineStatus(in *OscMachineStatus, out *v1beta2.OscMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineStatus_To_v1beta2_OscMachineStatus(in, out, s)
}

func autoConvert_v1beta2_OscMachineStatus_To_v1beta1_OscMachineStatus(in *v1beta2.OscMachineStatus, out *OscMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.VmState = (*VmState)(unsafe.Pointer(in.VmState))
	if err := Convert_v1beta2_OscNodeResource_To_v1beta1_OscNodeResource(&in.Node, &out.Node, s); err != nil {
		return err
	}
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta2_OscMachineStatus_To_v1beta1_OscMachineStatus is an autogenerated conversion function.
func Convert_v1beta2_OscMachineStatus_To_v1beta1_OscMachineStatus(in *v1beta2.OscMachineStatus, out *OscMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineStatus_To_v1beta1_OscMachineStatus(in, out, s)
}

func autoConvert_v1beta1_OscMachineTemplate_To_v1beta2_OscMachineTemplate(in *OscMachineTemplate, out *v1beta2.OscMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OscMachineTemplateSpec_To_v1beta2_OscMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscMachineTemplateStatus_To_v1beta2_OscMachineTemplateStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscMachineTemplate_To_v1beta2_OscMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_OscMachineTemplate_To_v1beta2_OscMachineTemplate(in *OscMachineTemplate, out *v1beta2.OscMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineTemplate_To_v1beta2_OscMachineTemplate(in, out, s)
}

func autoConvert_v1beta2_OscMachineTemplate_To_v1beta1_OscMachineTemplate(in *v1beta2.OscMachineTemplate, out *OscMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OscMachineTemplateSpec_To_v1beta1_OscMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscMachineTemplateStatus_To_v1beta1_OscMachineTemplateStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscMachineTemplate_To_v1beta1_OscMachineTemplate is an autogenerated conversion function.
func Convert_v1beta2_OscMachineTemplate_To_v1beta1_OscMachineTemplate(in *v1beta2.OscMachineTemplate, out *OscMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineTemplate_To_v1beta1_OscMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_OscMachineTemplateList_To_v1beta2_OscMachineTemplateList(in *OscMachineTemplateList, out *v1beta2.OscMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta2.OscMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_OscMachineTemplateList_To_v1beta2_OscMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_OscMachineTemplateList_To_v1beta2_OscMachineTemplateList(in *OscMachineTemplateList, out *v1beta2.OscMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineTemplateList_To_v1beta2_OscMachineTemplateList(in, out, s)
}

func autoConvert_v1beta2_OscMachineTemplateList_To_v1beta1_OscMachineTemplateList(in *v1beta2.OscMachineTemplateList, out *OscMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OscMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_OscMachineTemplateList_To_v1beta1_OscMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta2_OscMachineTemplateList_To_v1beta1_OscMachineTemplateList(in *v1beta2.OscMachineTemplateList, out *OscMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineTemplateList_To_v1beta1_OscMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_OscMachineTemplateResource_To_v1beta2_OscMachineTemplateResource(in *OscMachineTemplateResource, out *v1beta2.OscMachineTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OscMachineSpec_To_v1beta2_OscMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscMachineTemplateResource_To_v1beta2_OscMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_OscMachineTemplateResource_To_v1beta2_OscMachineTemplateResource(in *OscMachineTemplateResource, out *v1beta2.OscMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineTemplateResource_To_v1beta2_OscMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta2_OscMachineTemplateResource_To_v1beta1_OscMachineTemplateResource(in *v1beta2.OscMachineTemplateResource, out *OscMachineTemplateResource, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OscMachineSpec_To_v1beta1_OscMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscMachineTemplateResource_To_v1beta1_OscMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_OscMachineTemplateResource_To_v1beta1_OscMachineTemplateResource(in *v1beta2.OscMachineTemplateResource, out *OscMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineTemplateResource_To_v1beta1_OscMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_OscMachineTemplateSpec_To_v1beta2_OscMachineTemplateSpec(in *OscMachineTemplateSpec, out *v1beta2.OscMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_OscMachineTemplateResource_To_v1beta2_OscMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscMachineTemplateSpec_To_v1beta2_OscMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_OscMachineTemplateSpec_To_v1beta2_OscMachineTemplateSpec(in *OscMachineTemplateSpec, out *v1beta2.OscMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineTemplateSpec_To_v1beta2_OscMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_OscMachineTemplateSpec_To_v1beta1_OscMachineTemplateSpec(in *v1beta2.OscMachineTemplateSpec, out *OscMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_OscMachineTemplateResource_To_v1beta1_OscMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscMachineTemplateSpec_To_v1beta1_OscMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_OscMachineTemplateSpec_To_v1beta1_OscMachineTemplateSpec(in *v1beta2.OscMachineTemplateSpec, out *OscMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineTemplateSpec_To_v1beta1_OscMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_OscMachineTemplateStatus_To_v1beta2_OscMachineTemplateStatus(in *OscMachineTemplateStatus, out *v1beta2.OscMachineTemplateStatus, s conversion.Scope) error {
	out.Capacity = *(*v1.ResourceList)(unsafe.Pointer(&in.Capacity))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_OscMachineTemplateStatus_To_v1beta2_OscMachineTemplateStatus is an autogenerated conversion function.
func Convert_v1beta1_OscMachineTemplateStatus_To_v1beta2_OscMachineTemplateStatus(in *OscMachineTemplateStatus, out *v1beta2.OscMachineTemplateStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_OscMachineTemplateStatus_To_v1beta2_OscMachineTemplateStatus(in, out, s)
}

func autoConvert_v1beta2_OscMachineTemplateStatus_To_v1beta1_OscMachineTemplateStatus(in *v1beta2.OscMachineTemplateStatus, out *OscMachineTemplateStatus, s conversion.Scope) error {
	out.Capacity = *(*v1.ResourceList)(unsafe.Pointer(&in.Capacity))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta2_OscMachineTemplateStatus_To_v1beta1_OscMachineTemplateStatus is an autogenerated conversion function.
func Convert_v1beta2_OscMachineTemplateStatus_To_v1beta1_OscMachineTemplateStatus(in *v1beta2.OscMachineTemplateStatus, out *OscMachineTemplateStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_OscMachineTemplateStatus_To_v1beta1_OscMachineTemplateStatus(in, out, s)
}

func autoConvert_v1beta1_OscNatService_To_v1beta2_OscNatService(in *OscNatService, out *v1beta2.OscNatService, s conversion.Scope) error {
	out.Name = in.Name
	out.PublicIpName = in.PublicIpName
	out.SubnetName = in.SubnetName
	out.ClusterName = in.ClusterName
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscNatService_To_v1beta2_OscNatService is an autogenerated conversion function.
func Convert_v1beta1_OscNatService_To_v1beta2_OscNatService(in *OscNatService, out *v1beta2.OscNatService, s conversion.Scope) error {
	return autoConvert_v1beta1_OscNatService_To_v1beta2_OscNatService(in, out, s)
}

func autoConvert_v1beta2_OscNatService_To_v1beta1_OscNatService(in *v1beta2.OscNatService, out *OscNatService, s conversion.Scope) error {
	out.Name = in.Name
	out.PublicIpName = in.PublicIpName
	out.SubnetName = in.SubnetName
	out.ClusterName = in.ClusterName
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscNatService_To_v1beta1_OscNatService is an autogenerated conversion function.
func Convert_v1beta2_OscNatService_To_v1beta1_OscNatService(in *v1beta2.OscNatService, out *OscNatService, s conversion.Scope) error {
	return autoConvert_v1beta2_OscNatService_To_v1beta1_OscNatService(in, out, s)
}

func autoConvert_v1beta1_OscNet_To_v1beta2_OscNet(in *OscNet, out *v1beta2.OscNet, s conversion.Scope) error {
	out.Name = in.Name
	out.IpRange = in.IpRange
	out.ClusterName = in.ClusterName
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscNet_To_v1beta2_OscNet is an autogenerated conversion function.
func Convert_v1beta1_OscNet_To_v1beta2_OscNet(in *OscNet, out *v1beta2.OscNet, s conversion.Scope) error {
	return autoConvert_v1beta1_OscNet_To_v1beta2_OscNet(in, out, s)
}

func autoConvert_v1beta2_OscNet_To_v1beta1_OscNet(in *v1beta2.OscNet, out *OscNet, s conversion.Scope) error {
	out.Name = in.Name
	out.IpRange = in.IpRange
	out.ClusterName = in.ClusterName
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscNet_To_v1beta1_OscNet is an autogenerated conversion function.
func Convert_v1beta2_OscNet_To_v1beta1_OscNet(in *v1beta2.OscNet, out *OscNet, s conversion.Scope) error {
	return autoConvert_v1beta2_OscNet_To_v1beta1_OscNet(in, out, s)
}

// Convert_v1beta1_OscNetwork_To_v1beta2_OscNetwork is an autogenerated conversion function.
func Convert_v1beta1_OscNetwork_To_v1beta2_OscNetwork(in *OscNetwork, out *v1beta2.OscNetwork, s conversion.Scope) error {
	return autoConvert_v1beta1_OscNetwork_To_v1beta2_OscNetwork(in, out, s)
}

func autoConvert_v1beta1_OscNetworkResource_To_v1beta2_OscNetworkResource(in *OscNetworkResource, out *v1beta2.OscNetworkResource, s conversion.Scope) error {
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.NetRef, &out.NetRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.SubnetRef, &out.SubnetRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.InternetServiceRef, &out.InternetServiceRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.RouteTablesRef, &out.RouteTablesRef, s); err != nil {
		return err
	}
	// WARNING: in.LinkRouteTableRef requires manual conversion: inconvertible types (./api/v1beta1.OscResourceMapReference vs map[string][]string)
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.RouteRef, &out.RouteRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.SecurityGroupsRef, &out.SecurityGroupsRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.SecurityGroupRuleRef, &out.SecurityGroupRuleRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.PublicIpRef, &out.PublicIpRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.NatServiceRef, &out.NatServiceRef, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_OscNetworkResource_To_v1beta1_OscNetworkResource(in *v1beta2.OscNetworkResource, out *OscNetworkResource, s conversion.Scope) error {
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.NetRef, &out.NetRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.SubnetRef, &out.SubnetRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.InternetServiceRef, &out.InternetServiceRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.RouteTablesRef, &out.RouteTablesRef, s); err != nil {
		return err
	}
	// WARNING: in.LinkRouteTableRef requires manual conversion: inconvertible types (map[string][]string vs ./api/v1beta1.OscResourceMapReference)
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.RouteRef, &out.RouteRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.SecurityGroupsRef, &out.SecurityGroupsRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.SecurityGroupRuleRef, &out.SecurityGroupRuleRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.PublicIpRef, &out.PublicIpRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.NatServiceRef, &out.NatServiceRef, s); err != nil {
		return err
	}
	// WARNING: in.BastionRef requires manual conversion: does not exist in peer-type
	// WARNING: in.LinkPublicIpRef requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_v1beta1_OscNode_To_v1beta2_OscNode(in *OscNode, out *v1beta2.OscNode, s conversion.Scope) error {
	if err := Convert_v1beta1_OscVm_To_v1beta2_OscVm(&in.Vm, &out.Vm, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscImage_To_v1beta2_OscImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.Volumes = *(*[]*v1beta2.OscVolume)(unsafe.Pointer(&in.Volumes))
	if err := Convert_v1beta1_OscKeypair_To_v1beta2_OscKeypair(&in.KeyPair, &out.KeyPair, s); err != nil {
		return err
	}
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1beta1_OscNode_To_v1beta2_OscNode is an autogenerated conversion function.
func Convert_v1beta1_OscNode_To_v1beta2_OscNode(in *OscNode, out *v1beta2.OscNode, s conversion.Scope) error {
	return autoConvert_v1beta1_OscNode_To_v1beta2_OscNode(in, out, s)
}

func autoConvert_v1beta2_OscNode_To_v1beta1_OscNode(in *v1beta2.OscNode, out *OscNode, s conversion.Scope) error {
	if err := Convert_v1beta2_OscVm_To_v1beta1_OscVm(&in.Vm, &out.Vm, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscImage_To_v1beta1_OscImage(&in.Image, &out.Image, s); err != nil {
		return err
	}
	out.Volumes = *(*[]*OscVolume)(unsafe.Pointer(&in.Volumes))
	if err := Convert_v1beta2_OscKeypair_To_v1beta1_OscKeypair(&in.KeyPair, &out.KeyPair, s); err != nil {
		return err
	}
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1beta2_OscNode_To_v1beta1_OscNode is an autogenerated conversion function.
func Convert_v1beta2_OscNode_To_v1beta1_OscNode(in *v1beta2.OscNode, out *OscNode, s conversion.Scope) error {
	return autoConvert_v1beta2_OscNode_To_v1beta1_OscNode(in, out, s)
}

func autoConvert_v1beta1_OscNodeResource_To_v1beta2_OscNodeResource(in *OscNodeResource, out *v1beta2.OscNodeResource, s conversion.Scope) error {
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.VolumeRef, &out.VolumeRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.ImageRef, &out.ImageRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.KeypairRef, &out.KeypairRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.VmRef, &out.VmRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscResourceMapReference_To_v1beta2_OscResourceReference(&in.LinkPublicIpRef, &out.LinkPublicIpRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OscNodeResource_To_v1beta2_OscNodeResource is an autogenerated conversion function.
func Convert_v1beta1_OscNodeResource_To_v1beta2_OscNodeResource(in *OscNodeResource, out *v1beta2.OscNodeResource, s conversion.Scope) error {
	return autoConvert_v1beta1_OscNodeResource_To_v1beta2_OscNodeResource(in, out, s)
}

func autoConvert_v1beta2_OscNodeResource_To_v1beta1_OscNodeResource(in *v1beta2.OscNodeResource, out *OscNodeResource, s conversion.Scope) error {
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.VolumeRef, &out.VolumeRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.ImageRef, &out.ImageRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.KeypairRef, &out.KeypairRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.VmRef, &out.VmRef, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscResourceReference_To_v1beta1_OscResourceMapReference(&in.LinkPublicIpRef, &out.LinkPublicIpRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OscNodeResource_To_v1beta1_OscNodeResource is an autogenerated conversion function.
func Convert_v1beta2_OscNodeResource_To_v1beta1_OscNodeResource(in *v1beta2.OscNodeResource, out *OscNodeResource, s conversion.Scope) error {
	return autoConvert_v1beta2_OscNodeResource_To_v1beta1_OscNodeResource(in, out, s)
}

func autoConvert_v1beta1_OscPrivateIpElement_To_v1beta2_OscPrivateIpElement(in *OscPrivateIpElement, out *v1beta2.OscPrivateIpElement, s conversion.Scope) error {
	out.Name = in.Name
	out.PrivateIp = in.PrivateIp
	return nil
}

// Convert_v1beta1_OscPrivateIpElement_To_v1beta2_OscPrivateIpElement is an autogenerated conversion function.
func Convert_v1beta1_OscPrivateIpElement_To_v1beta2_OscPrivateIpElement(in *OscPrivateIpElement, out *v1beta2.OscPrivateIpElement, s conversion.Scope) error {
	return autoConvert_v1beta1_OscPrivateIpElement_To_v1beta2_OscPrivateIpElement(in, out, s)
}

func autoConvert_v1beta2_OscPrivateIpElement_To_v1beta1_OscPrivateIpElement(in *v1beta2.OscPrivateIpElement, out *OscPrivateIpElement, s conversion.Scope) error {
	out.Name = in.Name
	out.PrivateIp = in.PrivateIp
	return nil
}

// Convert_v1beta2_OscPrivateIpElement_To_v1beta1_OscPrivateIpElement is an autogenerated conversion function.
func Convert_v1beta2_OscPrivateIpElement_To_v1beta1_OscPrivateIpElement(in *v1beta2.OscPrivateIpElement, out *OscPrivateIpElement, s conversion.Scope) error {
	return autoConvert_v1beta2_OscPrivateIpElement_To_v1beta1_OscPrivateIpElement(in, out, s)
}

func autoConvert_v1beta1_OscPublicIp_To_v1beta2_OscPublicIp(in *OscPublicIp, out *v1beta2.OscPublicIp, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceId = in.ResourceId
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1beta1_OscPublicIp_To_v1beta2_OscPublicIp is an autogenerated conversion function.
func Convert_v1beta1_OscPublicIp_To_v1beta2_OscPublicIp(in *OscPublicIp, out *v1beta2.OscPublicIp, s conversion.Scope) error {
	return autoConvert_v1beta1_OscPublicIp_To_v1beta2_OscPublicIp(in, out, s)
}

func autoConvert_v1beta2_OscPublicIp_To_v1beta1_OscPublicIp(in *v1beta2.OscPublicIp, out *OscPublicIp, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceId = in.ResourceId
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1beta2_OscPublicIp_To_v1beta1_OscPublicIp is an autogenerated conversion function.
func Convert_v1beta2_OscPublicIp_To_v1beta1_OscPublicIp(in *v1beta2.OscPublicIp, out *OscPublicIp, s conversion.Scope) error {
	return autoConvert_v1beta2_OscPublicIp_To_v1beta1_OscPublicIp(in, out, s)
}

func autoConvert_v1beta1_OscRootDisk_To_v1beta2_OscRootDisk(in *OscRootDisk, out *v1beta2.OscRootDisk, s conversion.Scope) error {
	out.RootDiskIops = in.RootDiskIops
	out.RootDiskSize = in.RootDiskSize
	out.RootDiskType = in.RootDiskType
	return nil
}

// Convert_v1beta1_OscRootDisk_To_v1beta2_OscRootDisk is an autogenerated conversion function.
func Convert_v1beta1_OscRootDisk_To_v1beta2_OscRootDisk(in *OscRootDisk, out *v1beta2.OscRootDisk, s conversion.Scope) error {
	return autoConvert_v1beta1_OscRootDisk_To_v1beta2_OscRootDisk(in, out, s)
}

func autoConvert_v1beta2_OscRootDisk_To_v1beta1_OscRootDisk(in *v1beta2.OscRootDisk, out *OscRootDisk, s conversion.Scope) error {
	out.RootDiskIops = in.RootDiskIops
	out.RootDiskSize = in.RootDiskSize
	out.RootDiskType = in.RootDiskType
	return nil
}

// Convert_v1beta2_OscRootDisk_To_v1beta1_OscRootDisk is an autogenerated conversion function.
func Convert_v1beta2_OscRootDisk_To_v1beta1_OscRootDisk(in *v1beta2.OscRootDisk, out *OscRootDisk, s conversion.Scope) error {
	return autoConvert_v1beta2_OscRootDisk_To_v1beta1_OscRootDisk(in, out, s)
}

func autoConvert_v1beta1_OscRoute_To_v1beta2_OscRoute(in *OscRoute, out *v1beta2.OscRoute, s conversion.Scope) error {
	out.Name = in.Name
	out.TargetName = in.TargetName
	out.TargetType = in.TargetType
	out.Destination = in.Destination
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscRoute_To_v1beta2_OscRoute is an autogenerated conversion function.
func Convert_v1beta1_OscRoute_To_v1beta2_OscRoute(in *OscRoute, out *v1beta2.OscRoute, s conversion.Scope) error {
	return autoConvert_v1beta1_OscRoute_To_v1beta2_OscRoute(in, out, s)
}

func autoConvert_v1beta2_OscRoute_To_v1beta1_OscRoute(in *v1beta2.OscRoute, out *OscRoute, s conversion.Scope) error {
	out.Name = in.Name
	out.TargetName = in.TargetName
	out.TargetType = in.TargetType
	out.Destination = in.Destination
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscRoute_To_v1beta1_OscRoute is an autogenerated conversion function.
func Convert_v1beta2_OscRoute_To_v1beta1_OscRoute(in *v1beta2.OscRoute, out *OscRoute, s conversion.Scope) error {
	return autoConvert_v1beta2_OscRoute_To_v1beta1_OscRoute(in, out, s)
}

func autoConvert_v1beta1_OscRouteTable_To_v1beta2_OscRouteTable(in *OscRouteTable, out *v1beta2.OscRouteTable, s conversion.Scope) error {
	out.Name = in.Name
	// WARNING: in.SubnetName requires manual conversion: does not exist in peer-type
	out.Routes = *(*[]v1beta2.OscRoute)(unsafe.Pointer(&in.Routes))
	out.ResourceId = in.ResourceId
	return nil
}

func autoConvert_v1beta2_OscRouteTable_To_v1beta1_OscRouteTable(in *v1beta2.OscRouteTable, out *OscRouteTable, s conversion.Scope) error {
	out.Name = in.Name
	// WARNING: in.Subnets requires manual conversion: does not exist in peer-type
	out.Routes = *(*[]OscRoute)(unsafe.Pointer(&in.Routes))
	out.ResourceId = in.ResourceId
	return nil
}

func autoConvert_v1beta1_OscSecurityGroup_To_v1beta2_OscSecurityGroup(in *OscSecurityGroup, out *v1beta2.OscSecurityGroup, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.SecurityGroupRules = *(*[]v1beta2.OscSecurityGroupRule)(unsafe.Pointer(&in.SecurityGroupRules))
	out.ResourceId = in.ResourceId
	out.Tag = in.Tag
	return nil
}

// Convert_v1beta1_OscSecurityGroup_To_v1beta2_OscSecurityGroup is an autogenerated conversion function.
func Convert_v1beta1_OscSecurityGroup_To_v1beta2_OscSecurityGroup(in *OscSecurityGroup, out *v1beta2.OscSecurityGroup, s conversion.Scope) error {
	return autoConvert_v1beta1_OscSecurityGroup_To_v1beta2_OscSecurityGroup(in, out, s)
}

func autoConvert_v1beta2_OscSecurityGroup_To_v1beta1_OscSecurityGroup(in *v1beta2.OscSecurityGroup, out *OscSecurityGroup, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.SecurityGroupRules = *(*[]OscSecurityGroupRule)(unsafe.Pointer(&in.SecurityGroupRules))
	out.ResourceId = in.ResourceId
	out.Tag = in.Tag
	return nil
}

// Convert_v1beta2_OscSecurityGroup_To_v1beta1_OscSecurityGroup is an autogenerated conversion function.
func Convert_v1beta2_OscSecurityGroup_To_v1beta1_OscSecurityGroup(in *v1beta2.OscSecurityGroup, out *OscSecurityGroup, s conversion.Scope) error {
	return autoConvert_v1beta2_OscSecurityGroup_To_v1beta1_OscSecurityGroup(in, out, s)
}

func autoConvert_v1beta1_OscSecurityGroupElement_To_v1beta2_OscSecurityGroupElement(in *OscSecurityGroupElement, out *v1beta2.OscSecurityGroupElement, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1beta1_OscSecurityGroupElement_To_v1beta2_OscSecurityGroupElement is an autogenerated conversion function.
func Convert_v1beta1_OscSecurityGroupElement_To_v1beta2_OscSecurityGroupElement(in *OscSecurityGroupElement, out *v1beta2.OscSecurityGroupElement, s conversion.Scope) error {
	return autoConvert_v1beta1_OscSecurityGroupElement_To_v1beta2_OscSecurityGroupElement(in, out, s)
}

func autoConvert_v1beta2_OscSecurityGroupElement_To_v1beta1_OscSecurityGroupElement(in *v1beta2.OscSecurityGroupElement, out *OscSecurityGroupElement, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1beta2_OscSecurityGroupElement_To_v1beta1_OscSecurityGroupElement is an autogenerated conversion function.
func Convert_v1beta2_OscSecurityGroupElement_To_v1beta1_OscSecurityGroupElement(in *v1beta2.OscSecurityGroupElement, out *OscSecurityGroupElement, s conversion.Scope) error {
	return autoConvert_v1beta2_OscSecurityGroupElement_To_v1beta1_OscSecurityGroupElement(in, out, s)
}

func autoConvert_v1beta1_OscSecurityGroupRule_To_v1beta2_OscSecurityGroupRule(in *OscSecurityGroupRule, out *v1beta2.OscSecurityGroupRule, s conversion.Scope) error {
	out.Name = in.Name
	out.Flow = in.Flow
	out.IpProtocol = in.IpProtocol
	out.IpRange = in.IpRange
	out.FromPortRange = in.FromPortRange
	out.ToPortRange = in.ToPortRange
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscSecurityGroupRule_To_v1beta2_OscSecurityGroupRule is an autogenerated conversion function.
func Convert_v1beta1_OscSecurityGroupRule_To_v1beta2_OscSecurityGroupRule(in *OscSecurityGroupRule, out *v1beta2.OscSecurityGroupRule, s conversion.Scope) error {
	return autoConvert_v1beta1_OscSecurityGroupRule_To_v1beta2_OscSecurityGroupRule(in, out, s)
}

func autoConvert_v1beta2_OscSecurityGroupRule_To_v1beta1_OscSecurityGroupRule(in *v1beta2.OscSecurityGroupRule, out *OscSecurityGroupRule, s conversion.Scope) error {
	out.Name = in.Name
	out.Flow = in.Flow
	out.IpProtocol = in.IpProtocol
	out.IpRange = in.IpRange
	out.FromPortRange = in.FromPortRange
	out.ToPortRange = in.ToPortRange
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscSecurityGroupRule_To_v1beta1_OscSecurityGroupRule is an autogenerated conversion function.
func Convert_v1beta2_OscSecurityGroupRule_To_v1beta1_OscSecurityGroupRule(in *v1beta2.OscSecurityGroupRule, out *OscSecurityGroupRule, s conversion.Scope) error {
	return autoConvert_v1beta2_OscSecurityGroupRule_To_v1beta1_OscSecurityGroupRule(in, out, s)
}

func autoConvert_v1beta1_OscSubnet_To_v1beta2_OscSubnet(in *OscSubnet, out *v1beta2.OscSubnet, s conversion.Scope) error {
	out.Name = in.Name
	out.IpSubnetRange = in.IpSubnetRange
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscSubnet_To_v1beta2_OscSubnet is an autogenerated conversion function.
func Convert_v1beta1_OscSubnet_To_v1beta2_OscSubnet(in *OscSubnet, out *v1beta2.OscSubnet, s conversion.Scope) error {
	return autoConvert_v1beta1_OscSubnet_To_v1beta2_OscSubnet(in, out, s)
}

func autoConvert_v1beta2_OscSubnet_To_v1beta1_OscSubnet(in *v1beta2.OscSubnet, out *OscSubnet, s conversion.Scope) error {
	out.Name = in.Name
	out.IpSubnetRange = in.IpSubnetRange
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscSubnet_To_v1beta1_OscSubnet is an autogenerated conversion function.
func Convert_v1beta2_OscSubnet_To_v1beta1_OscSubnet(in *v1beta2.OscSubnet, out *OscSubnet, s conversion.Scope) error {
	return autoConvert_v1beta2_OscSubnet_To_v1beta1_OscSubnet(in, out, s)
}

func autoConvert_v1beta1_OscVm_To_v1beta2_OscVm(in *OscVm, out *v1beta2.OscVm, s conversion.Scope) error {
	out.Name = in.Name
	out.ImageId = in.ImageId
	out.KeypairName = in.KeypairName
	out.VmType = in.VmType
	out.VolumeName = in.VolumeName
	out.VolumeDeviceName = in.VolumeDeviceName
	out.DeviceName = in.DeviceName
	out.SubnetName = in.SubnetName
	if err := Convert_v1beta1_OscRootDisk_To_v1beta2_OscRootDisk(&in.RootDisk, &out.RootDisk, s); err != nil {
		return err
	}
	out.LoadBalancerName = in.LoadBalancerName
	out.PublicIpName = in.PublicIpName
	out.SubregionName = in.SubregionName
	out.PrivateIps = *(*[]v1beta2.OscPrivateIpElement)(unsafe.Pointer(&in.PrivateIps))
	out.SecurityGroupNames = *(*[]v1beta2.OscSecurityGroupElement)(unsafe.Pointer(&in.SecurityGroupNames))
	out.ResourceId = in.ResourceId
	out.Role = in.Role
	out.ClusterName = in.ClusterName
	out.Replica = in.Replica
	return nil
}

// Convert_v1beta1_OscVm_To_v1beta2_OscVm is an autogenerated conversion function.
func Convert_v1beta1_OscVm_To_v1beta2_OscVm(in *OscVm, out *v1beta2.OscVm, s conversion.Scope) error {
	return autoConvert_v1beta1_OscVm_To_v1beta2_OscVm(in, out, s)
}

func autoConvert_v1beta2_OscVm_To_v1beta1_OscVm(in *v1beta2.OscVm, out *OscVm, s conversion.Scope) error {
	out.Name = in.Name
	out.ImageId = in.ImageId
	out.KeypairName = in.KeypairName
	out.VmType = in.VmType
	out.VolumeName = in.VolumeName
	out.VolumeDeviceName = in.VolumeDeviceName
	out.DeviceName = in.DeviceName
	out.SubnetName = in.SubnetName
	if err := Convert_v1beta2_OscRootDisk_To_v1beta1_OscRootDisk(&in.RootDisk, &out.RootDisk, s); err != nil {
		return err
	}
	out.LoadBalancerName = in.LoadBalancerName
	out.PublicIpName = in.PublicIpName
	out.SubregionName = in.SubregionName
	out.PrivateIps = *(*[]OscPrivateIpElement)(unsafe.Pointer(&in.PrivateIps))
	out.SecurityGroupNames = *(*[]OscSecurityGroupElement)(unsafe.Pointer(&in.SecurityGroupNames))
	out.ResourceId = in.ResourceId
	out.Role = in.Role
	out.ClusterName = in.ClusterName
	out.Replica = in.Replica
	return nil
}

// Convert_v1beta2_OscVm_To_v1beta1_OscVm is an autogenerated conversion function.
func Convert_v1beta2_OscVm_To_v1beta1_OscVm(in *v1beta2.OscVm, out *OscVm, s conversion.Scope) error {
	return autoConvert_v1beta2_OscVm_To_v1beta1_OscVm(in, out, s)
}

func autoConvert_v1beta1_OscVolume_To_v1beta2_OscVolume(in *OscVolume, out *v1beta2.OscVolume, s conversion.Scope) error {
	out.Name = in.Name
	out.Iops = in.Iops
	out.Size = in.Size
	out.SubregionName = in.SubregionName
	out.VolumeType = in.VolumeType
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta1_OscVolume_To_v1beta2_OscVolume is an autogenerated conversion function.
func Convert_v1beta1_OscVolume_To_v1beta2_OscVolume(in *OscVolume, out *v1beta2.OscVolume, s conversion.Scope) error {
	return autoConvert_v1beta1_OscVolume_To_v1beta2_OscVolume(in, out, s)
}

func autoConvert_v1beta2_OscVolume_To_v1beta1_OscVolume(in *v1beta2.OscVolume, out *OscVolume, s conversion.Scope) error {
	out.Name = in.Name
	out.Iops = in.Iops
	out.Size = in.Size
	out.SubregionName = in.SubregionName
	out.VolumeType = in.VolumeType
	out.ResourceId = in.ResourceId
	return nil
}

// Convert_v1beta2_OscVolume_To_v1beta1_OscVolume is an autogenerated conversion function.
func Convert_v1beta2_OscVolume_To_v1beta1_OscVolume(in *v1beta2.OscVolume, out *OscVolume, s conversion.Scope) error {
	return autoConvert_v1beta2_OscVolume_To_v1beta1_OscVolume(in, out, s)
}

func autoConvert_v1beta1_OscNetwork_To_v1beta2_OscNetwork(in *OscNetwork, out *v1beta2.OscNetwork, s conversion.Scope) error {
	if err := Convert_v1beta1_OscLoadBalancer_To_v1beta2_OscLoadBalancer(&in.LoadBalancer, &out.LoadBalancer, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscNet_To_v1beta2_OscNet(&in.Net, &out.Net, s); err != nil {
		return err
	}
	out.Subnets = *(*[]*v1beta2.OscSubnet)(unsafe.Pointer(&in.Subnets))
	if err := Convert_v1beta1_OscInternetService_To_v1beta2_OscInternetService(&in.InternetService, &out.InternetService, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OscNatService_To_v1beta2_OscNatService(&in.NatService, &out.NatService, s); err != nil {
		return err
	}
	if in.RouteTables != nil {
		for _, outRouteTable := range out.RouteTables {
			for _, inRouteTable := range in.RouteTables {
				outRouteTable.Subnets[0] = inRouteTable.SubnetName
			}
		}
	} else {
		out.RouteTables = nil
	}
	out.Bastion.ClusterName = in.ClusterName
	out.SecurityGroups = *(*[]*v1beta2.OscSecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	out.PublicIps = *(*[]*v1beta2.OscPublicIp)(unsafe.Pointer(&in.PublicIps))
	out.ClusterName = in.ClusterName
	return nil
}

func autoConvert_v1beta1_OscMachineStatus_To_v1beta2_OscMachineStatus(in *OscMachineStatus, out *v1beta2.OscMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.VmState = (*v1beta2.VmState)(unsafe.Pointer(in.VmState))
	if err := Convert_v1beta1_OscNodeResource_To_v1beta2_OscNodeResource(&in.Node, &out.Node, s); err != nil {
		return err
	}
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

func autoConvert_v1beta2_OscNetwork_To_v1beta1_OscNetwork(in *v1beta2.OscNetwork, out *OscNetwork, s conversion.Scope) error {
	if err := Convert_v1beta2_OscLoadBalancer_To_v1beta1_OscLoadBalancer(&in.LoadBalancer, &out.LoadBalancer, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscNet_To_v1beta1_OscNet(&in.Net, &out.Net, s); err != nil {
		return err
	}
	out.Subnets = *(*[]*OscSubnet)(unsafe.Pointer(&in.Subnets))
	if err := Convert_v1beta2_OscInternetService_To_v1beta1_OscInternetService(&in.InternetService, &out.InternetService, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OscNatService_To_v1beta1_OscNatService(&in.NatService, &out.NatService, s); err != nil {
		return err
	}
	if in.RouteTables != nil {
		for _, outRouteTable := range out.RouteTables {
			for _, inRouteTable := range in.RouteTables {
				outRouteTable.SubnetName = inRouteTable.Subnets[0]
			}
		}
	} else {
		out.RouteTables = nil
	}

	out.SecurityGroups = *(*[]*OscSecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	out.PublicIps = *(*[]*OscPublicIp)(unsafe.Pointer(&in.PublicIps))
	out.ClusterName = in.ClusterName
	// WARNING: in.Image requires manual conversion: does not exist in peer-type
	// WARNING: in.Bastion requires manual conversion: does not exist in peer-type
	// WARNING: in.SubregionName requires manual conversion: does not exist in peer-type
	return nil
}
