//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	"sigs.k8s.io/cluster-api/errors"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscBastion) DeepCopyInto(out *OscBastion) {
	*out = *in
	out.RootDisk = in.RootDisk
	if in.PrivateIps != nil {
		in, out := &in.PrivateIps, &out.PrivateIps
		*out = make([]OscPrivateIpElement, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupNames != nil {
		in, out := &in.SecurityGroupNames, &out.SecurityGroupNames
		*out = make([]OscSecurityGroupElement, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscBastion.
func (in *OscBastion) DeepCopy() *OscBastion {
	if in == nil {
		return nil
	}
	out := new(OscBastion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscCluster) DeepCopyInto(out *OscCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscCluster.
func (in *OscCluster) DeepCopy() *OscCluster {
	if in == nil {
		return nil
	}
	out := new(OscCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterList) DeepCopyInto(out *OscClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OscCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterList.
func (in *OscClusterList) DeepCopy() *OscClusterList {
	if in == nil {
		return nil
	}
	out := new(OscClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterResources) DeepCopyInto(out *OscClusterResources) {
	*out = *in
	if in.Net != nil {
		in, out := &in.Net, &out.Net
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InternetService != nil {
		in, out := &in.InternetService, &out.InternetService
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecurityGroup != nil {
		in, out := &in.SecurityGroup, &out.SecurityGroup
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NatService != nil {
		in, out := &in.NatService, &out.NatService
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Bastion != nil {
		in, out := &in.Bastion, &out.Bastion
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PublicIPs != nil {
		in, out := &in.PublicIPs, &out.PublicIPs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterResources.
func (in *OscClusterResources) DeepCopy() *OscClusterResources {
	if in == nil {
		return nil
	}
	out := new(OscClusterResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterSpec) DeepCopyInto(out *OscClusterSpec) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterSpec.
func (in *OscClusterSpec) DeepCopy() *OscClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OscClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterStatus) DeepCopyInto(out *OscClusterStatus) {
	*out = *in
	in.Network.DeepCopyInto(&out.Network)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ReconcilerGeneration != nil {
		in, out := &in.ReconcilerGeneration, &out.ReconcilerGeneration
		*out = make(OscReconcilerGeneration, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make(apiv1beta1.FailureDomains, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VmState != nil {
		in, out := &in.VmState, &out.VmState
		*out = new(VmState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterStatus.
func (in *OscClusterStatus) DeepCopy() *OscClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OscClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterTemplate) DeepCopyInto(out *OscClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterTemplate.
func (in *OscClusterTemplate) DeepCopy() *OscClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(OscClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterTemplateList) DeepCopyInto(out *OscClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OscClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterTemplateList.
func (in *OscClusterTemplateList) DeepCopy() *OscClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(OscClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterTemplateResource) DeepCopyInto(out *OscClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterTemplateResource.
func (in *OscClusterTemplateResource) DeepCopy() *OscClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OscClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscClusterTemplateSpec) DeepCopyInto(out *OscClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscClusterTemplateSpec.
func (in *OscClusterTemplateSpec) DeepCopy() *OscClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OscClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscImage) DeepCopyInto(out *OscImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscImage.
func (in *OscImage) DeepCopy() *OscImage {
	if in == nil {
		return nil
	}
	out := new(OscImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscInternetService) DeepCopyInto(out *OscInternetService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscInternetService.
func (in *OscInternetService) DeepCopy() *OscInternetService {
	if in == nil {
		return nil
	}
	out := new(OscInternetService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscKeypair) DeepCopyInto(out *OscKeypair) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscKeypair.
func (in *OscKeypair) DeepCopy() *OscKeypair {
	if in == nil {
		return nil
	}
	out := new(OscKeypair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscLoadBalancer) DeepCopyInto(out *OscLoadBalancer) {
	*out = *in
	out.Listener = in.Listener
	out.HealthCheck = in.HealthCheck
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscLoadBalancer.
func (in *OscLoadBalancer) DeepCopy() *OscLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(OscLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscLoadBalancerHealthCheck) DeepCopyInto(out *OscLoadBalancerHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscLoadBalancerHealthCheck.
func (in *OscLoadBalancerHealthCheck) DeepCopy() *OscLoadBalancerHealthCheck {
	if in == nil {
		return nil
	}
	out := new(OscLoadBalancerHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscLoadBalancerListener) DeepCopyInto(out *OscLoadBalancerListener) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscLoadBalancerListener.
func (in *OscLoadBalancerListener) DeepCopy() *OscLoadBalancerListener {
	if in == nil {
		return nil
	}
	out := new(OscLoadBalancerListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachine) DeepCopyInto(out *OscMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachine.
func (in *OscMachine) DeepCopy() *OscMachine {
	if in == nil {
		return nil
	}
	out := new(OscMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineList) DeepCopyInto(out *OscMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OscMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineList.
func (in *OscMachineList) DeepCopy() *OscMachineList {
	if in == nil {
		return nil
	}
	out := new(OscMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineResources) DeepCopyInto(out *OscMachineResources) {
	*out = *in
	if in.Vm != nil {
		in, out := &in.Vm, &out.Vm
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineResources.
func (in *OscMachineResources) DeepCopy() *OscMachineResources {
	if in == nil {
		return nil
	}
	out := new(OscMachineResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineSpec) DeepCopyInto(out *OscMachineSpec) {
	*out = *in
	if in.ProviderID != nil {
		in, out := &in.ProviderID, &out.ProviderID
		*out = new(string)
		**out = **in
	}
	in.Node.DeepCopyInto(&out.Node)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineSpec.
func (in *OscMachineSpec) DeepCopy() *OscMachineSpec {
	if in == nil {
		return nil
	}
	out := new(OscMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineStatus) DeepCopyInto(out *OscMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]v1.NodeAddress, len(*in))
		copy(*out, *in)
	}
	if in.FailureDomain != nil {
		in, out := &in.FailureDomain, &out.FailureDomain
		*out = new(string)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(errors.MachineStatusError)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.VmState != nil {
		in, out := &in.VmState, &out.VmState
		*out = new(VmState)
		**out = **in
	}
	in.Node.DeepCopyInto(&out.Node)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ReconcilerGeneration != nil {
		in, out := &in.ReconcilerGeneration, &out.ReconcilerGeneration
		*out = make(OscReconcilerGeneration, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineStatus.
func (in *OscMachineStatus) DeepCopy() *OscMachineStatus {
	if in == nil {
		return nil
	}
	out := new(OscMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineTemplate) DeepCopyInto(out *OscMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineTemplate.
func (in *OscMachineTemplate) DeepCopy() *OscMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(OscMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineTemplateList) DeepCopyInto(out *OscMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OscMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineTemplateList.
func (in *OscMachineTemplateList) DeepCopy() *OscMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(OscMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OscMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineTemplateResource) DeepCopyInto(out *OscMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineTemplateResource.
func (in *OscMachineTemplateResource) DeepCopy() *OscMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OscMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineTemplateSpec) DeepCopyInto(out *OscMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineTemplateSpec.
func (in *OscMachineTemplateSpec) DeepCopy() *OscMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OscMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscMachineTemplateStatus) DeepCopyInto(out *OscMachineTemplateStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscMachineTemplateStatus.
func (in *OscMachineTemplateStatus) DeepCopy() *OscMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(OscMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscNatService) DeepCopyInto(out *OscNatService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscNatService.
func (in *OscNatService) DeepCopy() *OscNatService {
	if in == nil {
		return nil
	}
	out := new(OscNatService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscNet) DeepCopyInto(out *OscNet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscNet.
func (in *OscNet) DeepCopy() *OscNet {
	if in == nil {
		return nil
	}
	out := new(OscNet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscNetwork) DeepCopyInto(out *OscNetwork) {
	*out = *in
	out.LoadBalancer = in.LoadBalancer
	out.Net = in.Net
	if in.ControlPlaneSubnets != nil {
		in, out := &in.ControlPlaneSubnets, &out.ControlPlaneSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]OscSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.InternetService = in.InternetService
	out.NatService = in.NatService
	if in.NatServices != nil {
		in, out := &in.NatServices, &out.NatServices
		*out = make([]OscNatService, len(*in))
		copy(*out, *in)
	}
	if in.RouteTables != nil {
		in, out := &in.RouteTables, &out.RouteTables
		*out = make([]OscRouteTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]OscSecurityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PublicIps != nil {
		in, out := &in.PublicIps, &out.PublicIps
		*out = make([]*OscPublicIp, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(OscPublicIp)
				**out = **in
			}
		}
	}
	out.Image = in.Image
	in.Bastion.DeepCopyInto(&out.Bastion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscNetwork.
func (in *OscNetwork) DeepCopy() *OscNetwork {
	if in == nil {
		return nil
	}
	out := new(OscNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscNetworkResource) DeepCopyInto(out *OscNetworkResource) {
	*out = *in
	in.LoadbalancerRef.DeepCopyInto(&out.LoadbalancerRef)
	in.NetRef.DeepCopyInto(&out.NetRef)
	in.SubnetRef.DeepCopyInto(&out.SubnetRef)
	in.InternetServiceRef.DeepCopyInto(&out.InternetServiceRef)
	in.RouteTablesRef.DeepCopyInto(&out.RouteTablesRef)
	if in.LinkRouteTableRef != nil {
		in, out := &in.LinkRouteTableRef, &out.LinkRouteTableRef
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	in.RouteRef.DeepCopyInto(&out.RouteRef)
	in.SecurityGroupsRef.DeepCopyInto(&out.SecurityGroupsRef)
	in.SecurityGroupRuleRef.DeepCopyInto(&out.SecurityGroupRuleRef)
	in.PublicIpRef.DeepCopyInto(&out.PublicIpRef)
	in.NatServiceRef.DeepCopyInto(&out.NatServiceRef)
	in.BastionRef.DeepCopyInto(&out.BastionRef)
	in.LinkPublicIpRef.DeepCopyInto(&out.LinkPublicIpRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscNetworkResource.
func (in *OscNetworkResource) DeepCopy() *OscNetworkResource {
	if in == nil {
		return nil
	}
	out := new(OscNetworkResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscNode) DeepCopyInto(out *OscNode) {
	*out = *in
	in.Vm.DeepCopyInto(&out.Vm)
	out.Image = in.Image
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]OscVolume, len(*in))
		copy(*out, *in)
	}
	out.KeyPair = in.KeyPair
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscNode.
func (in *OscNode) DeepCopy() *OscNode {
	if in == nil {
		return nil
	}
	out := new(OscNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscNodeResource) DeepCopyInto(out *OscNodeResource) {
	*out = *in
	in.VolumeRef.DeepCopyInto(&out.VolumeRef)
	in.ImageRef.DeepCopyInto(&out.ImageRef)
	in.KeypairRef.DeepCopyInto(&out.KeypairRef)
	in.VmRef.DeepCopyInto(&out.VmRef)
	in.LinkPublicIpRef.DeepCopyInto(&out.LinkPublicIpRef)
	in.PublicIpIdRef.DeepCopyInto(&out.PublicIpIdRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscNodeResource.
func (in *OscNodeResource) DeepCopy() *OscNodeResource {
	if in == nil {
		return nil
	}
	out := new(OscNodeResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscPrivateIpElement) DeepCopyInto(out *OscPrivateIpElement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscPrivateIpElement.
func (in *OscPrivateIpElement) DeepCopy() *OscPrivateIpElement {
	if in == nil {
		return nil
	}
	out := new(OscPrivateIpElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscPublicIp) DeepCopyInto(out *OscPublicIp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscPublicIp.
func (in *OscPublicIp) DeepCopy() *OscPublicIp {
	if in == nil {
		return nil
	}
	out := new(OscPublicIp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in OscReconcilerGeneration) DeepCopyInto(out *OscReconcilerGeneration) {
	{
		in := &in
		*out = make(OscReconcilerGeneration, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscReconcilerGeneration.
func (in OscReconcilerGeneration) DeepCopy() OscReconcilerGeneration {
	if in == nil {
		return nil
	}
	out := new(OscReconcilerGeneration)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscResourceReference) DeepCopyInto(out *OscResourceReference) {
	*out = *in
	if in.ResourceMap != nil {
		in, out := &in.ResourceMap, &out.ResourceMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscResourceReference.
func (in *OscResourceReference) DeepCopy() *OscResourceReference {
	if in == nil {
		return nil
	}
	out := new(OscResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscRootDisk) DeepCopyInto(out *OscRootDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscRootDisk.
func (in *OscRootDisk) DeepCopy() *OscRootDisk {
	if in == nil {
		return nil
	}
	out := new(OscRootDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscRoute) DeepCopyInto(out *OscRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscRoute.
func (in *OscRoute) DeepCopy() *OscRoute {
	if in == nil {
		return nil
	}
	out := new(OscRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscRouteTable) DeepCopyInto(out *OscRouteTable) {
	*out = *in
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]OscRoute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscRouteTable.
func (in *OscRouteTable) DeepCopy() *OscRouteTable {
	if in == nil {
		return nil
	}
	out := new(OscRouteTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscSecurityGroup) DeepCopyInto(out *OscSecurityGroup) {
	*out = *in
	if in.SecurityGroupRules != nil {
		in, out := &in.SecurityGroupRules, &out.SecurityGroupRules
		*out = make([]OscSecurityGroupRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]OscRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscSecurityGroup.
func (in *OscSecurityGroup) DeepCopy() *OscSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(OscSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscSecurityGroupElement) DeepCopyInto(out *OscSecurityGroupElement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscSecurityGroupElement.
func (in *OscSecurityGroupElement) DeepCopy() *OscSecurityGroupElement {
	if in == nil {
		return nil
	}
	out := new(OscSecurityGroupElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscSecurityGroupRule) DeepCopyInto(out *OscSecurityGroupRule) {
	*out = *in
	if in.IpRanges != nil {
		in, out := &in.IpRanges, &out.IpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscSecurityGroupRule.
func (in *OscSecurityGroupRule) DeepCopy() *OscSecurityGroupRule {
	if in == nil {
		return nil
	}
	out := new(OscSecurityGroupRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscSubnet) DeepCopyInto(out *OscSubnet) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]OscRole, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscSubnet.
func (in *OscSubnet) DeepCopy() *OscSubnet {
	if in == nil {
		return nil
	}
	out := new(OscSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscVm) DeepCopyInto(out *OscVm) {
	*out = *in
	out.RootDisk = in.RootDisk
	if in.PrivateIps != nil {
		in, out := &in.PrivateIps, &out.PrivateIps
		*out = make([]OscPrivateIpElement, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupNames != nil {
		in, out := &in.SecurityGroupNames, &out.SecurityGroupNames
		*out = make([]OscSecurityGroupElement, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscVm.
func (in *OscVm) DeepCopy() *OscVm {
	if in == nil {
		return nil
	}
	out := new(OscVm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OscVolume) DeepCopyInto(out *OscVolume) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OscVolume.
func (in *OscVolume) DeepCopy() *OscVolume {
	if in == nil {
		return nil
	}
	out := new(OscVolume)
	in.DeepCopyInto(out)
	return out
}
