// Code generated by MockGen. DO NOT EDIT.
// Source: ./keypair.go

// Package mock_security is a generated GoMock package.
package mock_security

import (
	gomock "github.com/golang/mock/gomock"
	osc "github.com/outscale/osc-sdk-go/v2"
	reflect "reflect"
)

// MockOscKeyPairInterface is a mock of OscKeyPairInterface interface.
type MockOscKeyPairInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscKeyPairInterfaceMockRecorder
}

// MockOscKeyPairInterfaceMockRecorder is the mock recorder for MockOscKeyPairInterface.
type MockOscKeyPairInterfaceMockRecorder struct {
	mock *MockOscKeyPairInterface
}

// NewMockOscKeyPairInterface creates a new mock instance.
func NewMockOscKeyPairInterface(ctrl *gomock.Controller) *MockOscKeyPairInterface {
	mock := &MockOscKeyPairInterface{ctrl: ctrl}
	mock.recorder = &MockOscKeyPairInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscKeyPairInterface) EXPECT() *MockOscKeyPairInterfaceMockRecorder {
	return m.recorder
}

// CreateKeyPair mocks base method.
func (m *MockOscKeyPairInterface) CreateKeyPair(keypairName string) (*osc.KeypairCreated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyPair", keypairName)
	ret0, _ := ret[0].(*osc.KeypairCreated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyPair indicates an expected call of CreateKeyPair.
func (mr *MockOscKeyPairInterfaceMockRecorder) CreateKeyPair(keypairName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyPair", reflect.TypeOf((*MockOscKeyPairInterface)(nil).CreateKeyPair), keypairName)
}

// DeleteKeyPair mocks base method.
func (m *MockOscKeyPairInterface) DeleteKeyPair(keypairName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyPair", keypairName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeyPair indicates an expected call of DeleteKeyPair.
func (mr *MockOscKeyPairInterfaceMockRecorder) DeleteKeyPair(keypairName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyPair", reflect.TypeOf((*MockOscKeyPairInterface)(nil).DeleteKeyPair), keypairName)
}

// GetKeyPair mocks base method.
func (m *MockOscKeyPairInterface) GetKeyPair(keyPairName string) (*osc.Keypair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyPair", keyPairName)
	ret0, _ := ret[0].(*osc.Keypair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyPair indicates an expected call of GetKeyPair.
func (mr *MockOscKeyPairInterfaceMockRecorder) GetKeyPair(keyPairName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyPair", reflect.TypeOf((*MockOscKeyPairInterface)(nil).GetKeyPair), keyPairName)
}
