// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -destination mock_compute/compute_mock.go -package mock_compute -source ./service.go
//

// Package mock_compute is a generated GoMock package.
package mock_compute

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/outscale/cluster-api-provider-outscale/api/v1beta1"
	scope "github.com/outscale/cluster-api-provider-outscale/cloud/scope"
	osc "github.com/outscale/osc-sdk-go/v3/pkg/osc"
	gomock "go.uber.org/mock/gomock"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
	isgomock struct{}
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// AddCCMTags mocks base method.
func (m *MockServicer) AddCCMTags(ctx context.Context, clusterName, hostname, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCCMTags", ctx, clusterName, hostname, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCCMTags indicates an expected call of AddCCMTags.
func (mr *MockServicerMockRecorder) AddCCMTags(ctx, clusterName, hostname, vmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCCMTags", reflect.TypeOf((*MockServicer)(nil).AddCCMTags), ctx, clusterName, hostname, vmId)
}

// AllocateFGPU mocks base method.
func (m *MockServicer) AllocateFGPU(ctx context.Context, model, az string, machineScope *scope.MachineScope) (*osc.FlexibleGpu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateFGPU", ctx, model, az, machineScope)
	ret0, _ := ret[0].(*osc.FlexibleGpu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateFGPU indicates an expected call of AllocateFGPU.
func (mr *MockServicerMockRecorder) AllocateFGPU(ctx, model, az, machineScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateFGPU", reflect.TypeOf((*MockServicer)(nil).AllocateFGPU), ctx, model, az, machineScope)
}

// CreateSecurityGroup mocks base method.
func (m *MockServicer) CreateSecurityGroup(ctx context.Context, netId, clusterID, securityGroupName, securityGroupDescription, securityGroupTag string, roles []v1beta1.OscRole) (*osc.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroup", ctx, netId, clusterID, securityGroupName, securityGroupDescription, securityGroupTag, roles)
	ret0, _ := ret[0].(*osc.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecurityGroup indicates an expected call of CreateSecurityGroup.
func (mr *MockServicerMockRecorder) CreateSecurityGroup(ctx, netId, clusterID, securityGroupName, securityGroupDescription, securityGroupTag, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroup", reflect.TypeOf((*MockServicer)(nil).CreateSecurityGroup), ctx, netId, clusterID, securityGroupName, securityGroupDescription, securityGroupTag, roles)
}

// CreateSecurityGroupRule mocks base method.
func (m *MockServicer) CreateSecurityGroupRule(ctx context.Context, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId string, fromPortRange, toPortRange int) (*osc.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityGroupRule", ctx, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId, fromPortRange, toPortRange)
	ret0, _ := ret[0].(*osc.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecurityGroupRule indicates an expected call of CreateSecurityGroupRule.
func (mr *MockServicerMockRecorder) CreateSecurityGroupRule(ctx, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId, fromPortRange, toPortRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityGroupRule", reflect.TypeOf((*MockServicer)(nil).CreateSecurityGroupRule), ctx, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId, fromPortRange, toPortRange)
}

// CreateVm mocks base method.
func (m *MockServicer) CreateVm(ctx context.Context, machineScope *scope.MachineScope, spec *v1beta1.OscVm, imageId, subnetId string, securityGroupIds, privateIps []string, vmName, vmClientToken string, tags map[string]string, volumes []v1beta1.OscVolume) (*osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVm", ctx, machineScope, spec, imageId, subnetId, securityGroupIds, privateIps, vmName, vmClientToken, tags, volumes)
	ret0, _ := ret[0].(*osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVm indicates an expected call of CreateVm.
func (mr *MockServicerMockRecorder) CreateVm(ctx, machineScope, spec, imageId, subnetId, securityGroupIds, privateIps, vmName, vmClientToken, tags, volumes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVm", reflect.TypeOf((*MockServicer)(nil).CreateVm), ctx, machineScope, spec, imageId, subnetId, securityGroupIds, privateIps, vmName, vmClientToken, tags, volumes)
}

// CreateVmBastion mocks base method.
func (m *MockServicer) CreateVmBastion(ctx context.Context, spec *v1beta1.OscBastion, subnetId string, securityGroupIds, privateIps []string, vmName, vmClientToken, imageId string, tags map[string]string) (*osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVmBastion", ctx, spec, subnetId, securityGroupIds, privateIps, vmName, vmClientToken, imageId, tags)
	ret0, _ := ret[0].(*osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVmBastion indicates an expected call of CreateVmBastion.
func (mr *MockServicerMockRecorder) CreateVmBastion(ctx, spec, subnetId, securityGroupIds, privateIps, vmName, vmClientToken, imageId, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVmBastion", reflect.TypeOf((*MockServicer)(nil).CreateVmBastion), ctx, spec, subnetId, securityGroupIds, privateIps, vmName, vmClientToken, imageId, tags)
}

// DeleteSecurityGroup mocks base method.
func (m *MockServicer) DeleteSecurityGroup(ctx context.Context, securityGroupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityGroup", ctx, securityGroupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecurityGroup indicates an expected call of DeleteSecurityGroup.
func (mr *MockServicerMockRecorder) DeleteSecurityGroup(ctx, securityGroupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityGroup", reflect.TypeOf((*MockServicer)(nil).DeleteSecurityGroup), ctx, securityGroupId)
}

// DeleteSecurityGroupRule mocks base method.
func (m *MockServicer) DeleteSecurityGroupRule(ctx context.Context, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId string, fromPortRange, toPortRange int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecurityGroupRule", ctx, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId, fromPortRange, toPortRange)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecurityGroupRule indicates an expected call of DeleteSecurityGroupRule.
func (mr *MockServicerMockRecorder) DeleteSecurityGroupRule(ctx, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId, fromPortRange, toPortRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecurityGroupRule", reflect.TypeOf((*MockServicer)(nil).DeleteSecurityGroupRule), ctx, securityGroupId, flow, ipProtocol, ipRange, securityGroupMemberId, fromPortRange, toPortRange)
}

// DeleteVm mocks base method.
func (m *MockServicer) DeleteVm(ctx context.Context, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVm", ctx, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVm indicates an expected call of DeleteVm.
func (mr *MockServicerMockRecorder) DeleteVm(ctx, vmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVm", reflect.TypeOf((*MockServicer)(nil).DeleteVm), ctx, vmId)
}

// GetFGPU mocks base method.
func (m *MockServicer) GetFGPU(ctx context.Context, id string) (*osc.FlexibleGpu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFGPU", ctx, id)
	ret0, _ := ret[0].(*osc.FlexibleGpu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFGPU indicates an expected call of GetFGPU.
func (mr *MockServicerMockRecorder) GetFGPU(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFGPU", reflect.TypeOf((*MockServicer)(nil).GetFGPU), ctx, id)
}

// GetImage mocks base method.
func (m *MockServicer) GetImage(ctx context.Context, id string) (*osc.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id)
	ret0, _ := ret[0].(*osc.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockServicerMockRecorder) GetImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockServicer)(nil).GetImage), ctx, id)
}

// GetImageByName mocks base method.
func (m *MockServicer) GetImageByName(ctx context.Context, name, accountId string) (*osc.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageByName", ctx, name, accountId)
	ret0, _ := ret[0].(*osc.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageByName indicates an expected call of GetImageByName.
func (mr *MockServicerMockRecorder) GetImageByName(ctx, name, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageByName", reflect.TypeOf((*MockServicer)(nil).GetImageByName), ctx, name, accountId)
}

// GetSecurityGroup mocks base method.
func (m *MockServicer) GetSecurityGroup(ctx context.Context, securityGroupId string) (*osc.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroup", ctx, securityGroupId)
	ret0, _ := ret[0].(*osc.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroup indicates an expected call of GetSecurityGroup.
func (mr *MockServicerMockRecorder) GetSecurityGroup(ctx, securityGroupId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroup", reflect.TypeOf((*MockServicer)(nil).GetSecurityGroup), ctx, securityGroupId)
}

// GetSecurityGroupFromName mocks base method.
func (m *MockServicer) GetSecurityGroupFromName(ctx context.Context, name string) (*osc.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupFromName", ctx, name)
	ret0, _ := ret[0].(*osc.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupFromName indicates an expected call of GetSecurityGroupFromName.
func (mr *MockServicerMockRecorder) GetSecurityGroupFromName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupFromName", reflect.TypeOf((*MockServicer)(nil).GetSecurityGroupFromName), ctx, name)
}

// GetSecurityGroupsFromNet mocks base method.
func (m *MockServicer) GetSecurityGroupsFromNet(ctx context.Context, netId string) ([]osc.SecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityGroupsFromNet", ctx, netId)
	ret0, _ := ret[0].([]osc.SecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityGroupsFromNet indicates an expected call of GetSecurityGroupsFromNet.
func (mr *MockServicerMockRecorder) GetSecurityGroupsFromNet(ctx, netId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityGroupsFromNet", reflect.TypeOf((*MockServicer)(nil).GetSecurityGroupsFromNet), ctx, netId)
}

// GetVm mocks base method.
func (m *MockServicer) GetVm(ctx context.Context, vmId string) (*osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVm", ctx, vmId)
	ret0, _ := ret[0].(*osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVm indicates an expected call of GetVm.
func (mr *MockServicerMockRecorder) GetVm(ctx, vmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVm", reflect.TypeOf((*MockServicer)(nil).GetVm), ctx, vmId)
}

// GetVmFromClientToken mocks base method.
func (m *MockServicer) GetVmFromClientToken(ctx context.Context, clientToken string) (*osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVmFromClientToken", ctx, clientToken)
	ret0, _ := ret[0].(*osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVmFromClientToken indicates an expected call of GetVmFromClientToken.
func (mr *MockServicerMockRecorder) GetVmFromClientToken(ctx, clientToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVmFromClientToken", reflect.TypeOf((*MockServicer)(nil).GetVmFromClientToken), ctx, clientToken)
}

// LinkFGPU mocks base method.
func (m *MockServicer) LinkFGPU(ctx context.Context, fGPUId, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkFGPU", ctx, fGPUId, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkFGPU indicates an expected call of LinkFGPU.
func (mr *MockServicerMockRecorder) LinkFGPU(ctx, fGPUId, vmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkFGPU", reflect.TypeOf((*MockServicer)(nil).LinkFGPU), ctx, fGPUId, vmId)
}

// SecurityGroupHasRule mocks base method.
func (m *MockServicer) SecurityGroupHasRule(ctx context.Context, securityGroupId, flow, ipProtocols, ipRanges, securityGroupMemberId string, fromPortRanges, toPortRanges int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecurityGroupHasRule", ctx, securityGroupId, flow, ipProtocols, ipRanges, securityGroupMemberId, fromPortRanges, toPortRanges)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecurityGroupHasRule indicates an expected call of SecurityGroupHasRule.
func (mr *MockServicerMockRecorder) SecurityGroupHasRule(ctx, securityGroupId, flow, ipProtocols, ipRanges, securityGroupMemberId, fromPortRanges, toPortRanges any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecurityGroupHasRule", reflect.TypeOf((*MockServicer)(nil).SecurityGroupHasRule), ctx, securityGroupId, flow, ipProtocols, ipRanges, securityGroupMemberId, fromPortRanges, toPortRanges)
}

// StartVm mocks base method.
func (m *MockServicer) StartVm(ctx context.Context, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartVm", ctx, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartVm indicates an expected call of StartVm.
func (mr *MockServicerMockRecorder) StartVm(ctx, vmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartVm", reflect.TypeOf((*MockServicer)(nil).StartVm), ctx, vmId)
}

// StopVm mocks base method.
func (m *MockServicer) StopVm(ctx context.Context, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopVm", ctx, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopVm indicates an expected call of StopVm.
func (mr *MockServicerMockRecorder) StopVm(ctx, vmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopVm", reflect.TypeOf((*MockServicer)(nil).StopVm), ctx, vmId)
}
