// Code generated by MockGen. DO NOT EDIT.
// Source: ./fgpu.go
//
// Generated by this command:
//
//	mockgen -destination mock_compute/fgpu_mock.go -package mock_compute -source ./fgpu.go
//

// Package mock_compute is a generated GoMock package.
package mock_compute

import (
	context "context"
	reflect "reflect"

	scope "github.com/outscale/cluster-api-provider-outscale/cloud/scope"
	osc "github.com/outscale/osc-sdk-go/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockOscFGPUInterface is a mock of OscFGPUInterface interface.
type MockOscFGPUInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscFGPUInterfaceMockRecorder
	isgomock struct{}
}

// MockOscFGPUInterfaceMockRecorder is the mock recorder for MockOscFGPUInterface.
type MockOscFGPUInterfaceMockRecorder struct {
	mock *MockOscFGPUInterface
}

// NewMockOscFGPUInterface creates a new mock instance.
func NewMockOscFGPUInterface(ctrl *gomock.Controller) *MockOscFGPUInterface {
	mock := &MockOscFGPUInterface{ctrl: ctrl}
	mock.recorder = &MockOscFGPUInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscFGPUInterface) EXPECT() *MockOscFGPUInterfaceMockRecorder {
	return m.recorder
}

// AllocateFGPU mocks base method.
func (m *MockOscFGPUInterface) AllocateFGPU(ctx context.Context, model, az string, machineScope *scope.MachineScope) (*osc.FlexibleGpu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateFGPU", ctx, model, az, machineScope)
	ret0, _ := ret[0].(*osc.FlexibleGpu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateFGPU indicates an expected call of AllocateFGPU.
func (mr *MockOscFGPUInterfaceMockRecorder) AllocateFGPU(ctx, model, az, machineScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateFGPU", reflect.TypeOf((*MockOscFGPUInterface)(nil).AllocateFGPU), ctx, model, az, machineScope)
}

// GetFGPU mocks base method.
func (m *MockOscFGPUInterface) GetFGPU(ctx context.Context, id string) (*osc.FlexibleGpu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFGPU", ctx, id)
	ret0, _ := ret[0].(*osc.FlexibleGpu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFGPU indicates an expected call of GetFGPU.
func (mr *MockOscFGPUInterfaceMockRecorder) GetFGPU(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFGPU", reflect.TypeOf((*MockOscFGPUInterface)(nil).GetFGPU), ctx, id)
}

// LinkFGPU mocks base method.
func (m *MockOscFGPUInterface) LinkFGPU(ctx context.Context, fGPUId, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkFGPU", ctx, fGPUId, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkFGPU indicates an expected call of LinkFGPU.
func (mr *MockOscFGPUInterfaceMockRecorder) LinkFGPU(ctx, fGPUId, vmId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkFGPU", reflect.TypeOf((*MockOscFGPUInterface)(nil).LinkFGPU), ctx, fGPUId, vmId)
}
