// Code generated by MockGen. DO NOT EDIT.
// Source: ./image.go

// Package mock_compute is a generated GoMock package.
package mock_compute

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	osc "github.com/outscale/osc-sdk-go/v2"
)

// MockOscImageInterface is a mock of OscImageInterface interface.
type MockOscImageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscImageInterfaceMockRecorder
}

// MockOscImageInterfaceMockRecorder is the mock recorder for MockOscImageInterface.
type MockOscImageInterfaceMockRecorder struct {
	mock *MockOscImageInterface
}

// NewMockOscImageInterface creates a new mock instance.
func NewMockOscImageInterface(ctrl *gomock.Controller) *MockOscImageInterface {
	mock := &MockOscImageInterface{ctrl: ctrl}
	mock.recorder = &MockOscImageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscImageInterface) EXPECT() *MockOscImageInterfaceMockRecorder {
	return m.recorder
}

// GetImage mocks base method.
func (m *MockOscImageInterface) GetImage(ctx context.Context, imageId string) (*osc.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, imageId)
	ret0, _ := ret[0].(*osc.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockOscImageInterfaceMockRecorder) GetImage(ctx, imageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockOscImageInterface)(nil).GetImage), ctx, imageId)
}

// GetImageByName mocks base method.
func (m *MockOscImageInterface) GetImageByName(ctx context.Context, imageName, accountId string) (*osc.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageByName", ctx, imageName, accountId)
	ret0, _ := ret[0].(*osc.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageByName indicates an expected call of GetImageByName.
func (mr *MockOscImageInterfaceMockRecorder) GetImageByName(ctx, imageName, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageByName", reflect.TypeOf((*MockOscImageInterface)(nil).GetImageByName), ctx, imageName, accountId)
}
