// Code generated by MockGen. DO NOT EDIT.
// Source: ./vm.go

// Package mock_compute is a generated GoMock package.
package mock_compute

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1beta1 "github.com/outscale/cluster-api-provider-outscale/api/v1beta1"
	scope "github.com/outscale/cluster-api-provider-outscale/cloud/scope"
	osc "github.com/outscale/osc-sdk-go/v2"
)

// MockOscVmInterface is a mock of OscVmInterface interface.
type MockOscVmInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscVmInterfaceMockRecorder
}

// MockOscVmInterfaceMockRecorder is the mock recorder for MockOscVmInterface.
type MockOscVmInterfaceMockRecorder struct {
	mock *MockOscVmInterface
}

// NewMockOscVmInterface creates a new mock instance.
func NewMockOscVmInterface(ctrl *gomock.Controller) *MockOscVmInterface {
	mock := &MockOscVmInterface{ctrl: ctrl}
	mock.recorder = &MockOscVmInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscVmInterface) EXPECT() *MockOscVmInterfaceMockRecorder {
	return m.recorder
}

// AddCcmTag mocks base method.
func (m *MockOscVmInterface) AddCcmTag(ctx context.Context, clusterName, hostname, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCcmTag", ctx, clusterName, hostname, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCcmTag indicates an expected call of AddCcmTag.
func (mr *MockOscVmInterfaceMockRecorder) AddCcmTag(ctx, clusterName, hostname, vmId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCcmTag", reflect.TypeOf((*MockOscVmInterface)(nil).AddCcmTag), ctx, clusterName, hostname, vmId)
}

// CreateVm mocks base method.
func (m *MockOscVmInterface) CreateVm(ctx context.Context, machineScope *scope.MachineScope, spec *v1beta1.OscVm, subnetId string, securityGroupIds, privateIps []string, vmName string, tags map[string]string) (*osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVm", ctx, machineScope, spec, subnetId, securityGroupIds, privateIps, vmName, tags)
	ret0, _ := ret[0].(*osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVm indicates an expected call of CreateVm.
func (mr *MockOscVmInterfaceMockRecorder) CreateVm(ctx, machineScope, spec, subnetId, securityGroupIds, privateIps, vmName, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVm", reflect.TypeOf((*MockOscVmInterface)(nil).CreateVm), ctx, machineScope, spec, subnetId, securityGroupIds, privateIps, vmName, tags)
}

// CreateVmUserData mocks base method.
func (m *MockOscVmInterface) CreateVmUserData(ctx context.Context, userData string, spec *v1beta1.OscBastion, subnetId string, securityGroupIds, privateIps []string, vmName, imageId string) (*osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVmUserData", ctx, userData, spec, subnetId, securityGroupIds, privateIps, vmName, imageId)
	ret0, _ := ret[0].(*osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVmUserData indicates an expected call of CreateVmUserData.
func (mr *MockOscVmInterfaceMockRecorder) CreateVmUserData(ctx, userData, spec, subnetId, securityGroupIds, privateIps, vmName, imageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVmUserData", reflect.TypeOf((*MockOscVmInterface)(nil).CreateVmUserData), ctx, userData, spec, subnetId, securityGroupIds, privateIps, vmName, imageId)
}

// DeleteVm mocks base method.
func (m *MockOscVmInterface) DeleteVm(ctx context.Context, vmId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVm", ctx, vmId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVm indicates an expected call of DeleteVm.
func (mr *MockOscVmInterfaceMockRecorder) DeleteVm(ctx, vmId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVm", reflect.TypeOf((*MockOscVmInterface)(nil).DeleteVm), ctx, vmId)
}

// GetVm mocks base method.
func (m *MockOscVmInterface) GetVm(ctx context.Context, vmId string) (*osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVm", ctx, vmId)
	ret0, _ := ret[0].(*osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVm indicates an expected call of GetVm.
func (mr *MockOscVmInterfaceMockRecorder) GetVm(ctx, vmId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVm", reflect.TypeOf((*MockOscVmInterface)(nil).GetVm), ctx, vmId)
}

// GetVmListFromTag mocks base method.
func (m *MockOscVmInterface) GetVmListFromTag(ctx context.Context, tagKey, tagName string) ([]osc.Vm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVmListFromTag", ctx, tagKey, tagName)
	ret0, _ := ret[0].([]osc.Vm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVmListFromTag indicates an expected call of GetVmListFromTag.
func (mr *MockOscVmInterfaceMockRecorder) GetVmListFromTag(ctx, tagKey, tagName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVmListFromTag", reflect.TypeOf((*MockOscVmInterface)(nil).GetVmListFromTag), ctx, tagKey, tagName)
}

// GetVmState mocks base method.
func (m *MockOscVmInterface) GetVmState(ctx context.Context, vmId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVmState", ctx, vmId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVmState indicates an expected call of GetVmState.
func (mr *MockOscVmInterfaceMockRecorder) GetVmState(ctx, vmId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVmState", reflect.TypeOf((*MockOscVmInterface)(nil).GetVmState), ctx, vmId)
}
