name: all E2E tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/all-e2e-test.yaml"

permissions:
  contents: read

jobs:
  e2e-all:
    runs-on: [self-hosted, linux]
    steps:
    - name: 🩹 Safe config for 💩 DNS
      run: |
        sed 's/options /options use-vc single-request attempts:5 /' < /etc/resolv.conf > /etc/resolv.conf.new
        cat /etc/resolv.conf.new > /etc/resolv.conf
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: ⬇️ Install kubectl
      uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0
      with:
        version: v1.34.9
    - name: ⬇️ Install helm
      uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      with:
        version: v3.21.3
    - name: ⬇️ Install kustomize
      uses: imranismail/setup-kustomize@53f941b41dca13ed61874bbc6b4b6e1562877530 # v3.0.0
      with:
        kustomize-version: 5.7.1
    - name: 🔎 Check IP
      id: ip
      run: |
        echo "ip=`curl -s https://api.ipify.org`" | tee $GITHUB_OUTPUT
    - name: 🔐 Set ak/sk name based on runner region
      run: .github/scripts/runneraksk.sh
    - name: ⬇️ Install octl
      uses: outscale/octl/.github/actions/setup_octl@29f89fd6d31b0d9180f182b8eb85904afb4231fc # v0.0.30
      with:
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@1d8b83bc64d2230a0c3bc9f018ba6c0c67df98e8 # v0.15.0+hotfix.0
      with:
        access_key: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        secret_key: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        region: ${{ env.OSC_REGION }}
        exclude_resource_types: access_key
    - name: 👷 Deploy management cluster
      id: management
      uses: ./.github/actions/deploy_cluster
      with:
        RUNNER_NAME: ${{ runner.name }}
        OKS_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY_OKS }}
        OKS_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY_OKS }}
        OKS_REGION: ${{ vars.OKS_REGION }}
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        CLUSTER_NAME: "caposc-all"
        IMAGE_NAME: ${{ vars.IMG_MANAGEMENT }}
        IMAGE_ACCOUNT_ID: ${{ secrets[env.OSC_ACCOUNT_ID_NAME] }}
        CERT_MANAGER: "true"
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: 📦 Run GoReleaser
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        version: 'v2.15.4'
        args: release --clean --snapshot
    - name: 🐳 Login to Harbor
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: ${{ vars.REGISTRY }}
        username: admin
        password: ${{ secrets.HARBOR_ADMIN_PASSWORD }}
    - name: 📦 Push Docker image
      run: |
        make image-tag image-push
      env:
        IMAGE: "outscale/cluster-api-outscale-controllers"
        IMAGE_TAG: "${{ github.sha }}-amd64"
        REGISTRY_IMAGE: "${{ vars.REGISTRY }}/outscale/cluster-api-outscale-controllers"
        REGISTRY_TAG: ${{ github.sha }}
    - name: 🔎 Preloader snapshot
      id: preloader
      uses: outscale/k8s-image-preloader/github_actions/preloader_snapshot@5208a47fe34662d21c901d32f739ba44a2567d52 # main
      with:
        KUBECONFIG: ${{ steps.management.outputs.KUBECONFIG }}
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        CSI: true
    - name: 🔐 Create CAPOSC ns and credentials
      run: make credentials
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.management.outputs.KUBECONFIG }}"
    - name: 🧪 Launch e2e tests
      run: |
        from=`echo ${{ vars.IMG_UPGRADE_FROM }} | sed 's/.*kubernetes-\(v[^-]*\)-.*/\1/'`
        to=`echo ${{ vars.IMG_UPGRADE_TO }} | sed 's/.*kubernetes-\(v[^-]*\)-.*/\1/'`
        export KUBERNETES_VERSION=$from
        export KUBERNETES_VERSION_UPGRADE_FROM=$from
        export KUBERNETES_VERSION_UPGRADE_TO=$to
        E2E_FOCUS=all make e2etest
      shell: bash
      id: e2etest
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.management.outputs.KUBECONFIG }}"
        CCM_OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        CCM_OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        CCM_OSC_REGION: ${{ env.OSC_REGION }}
        IMG: ${{ vars.REGISTRY }}/outscale/cluster-api-outscale-controllers:${{ github.sha }}
        IMG_UPGRADE_FROM: ${{ vars.IMG_UPGRADE_FROM }}
        IMG_UPGRADE_TO: ${{ vars.IMG_UPGRADE_TO }}
        COREDNS_VERSION_UPGRADE_TO: ${{ vars.COREDNS_VERSION_UPGRADE_TO }}
        ETCD_VERSION_UPGRADE_TO: ${{ vars.ETCD_VERSION_UPGRADE_TO }}
        PRELOAD_SNAPSHOT_ID: ${{ steps.preloader.outputs.SNAPSHOT_ID }}
    - name: 📝 Get CAPOSC state/logs
      run: |
        echo "**** pod state"
        kubectl describe po -n cluster-api-provider-outscale-system
        echo "**** pod logs"
        make logs-capo
      if: ${{ failure() && steps.e2etest.conclusion == 'failure' }}
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.management.outputs.KUBECONFIG }}"
        CAPO_NAMESPACE: cluster-api-provider-outscale-system
    - name: 📝 Get cluster api logs
      run: make logs-capi
      if: ${{ failure() && steps.e2etest.conclusion == 'failure' }}
      shell: bash
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.management.outputs.KUBECONFIG }}"
        CAPI_NAMESPACE: capi-kubeadm-bootstrap-system
