name: Check build & lint

on:
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "**.yaml"
      - "**.mod"
      - "**.sum"
      - "!capm.yaml"
      - "!osc-secret.yaml"
      - "!example/**.yaml"
      - "!helm/**"
      - "Makefile"
      - "Dockerfile"
      - "!docs/src/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: ⬇️ Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
      - name: 🔎 golangci-lint
        uses: outscale/goutils/.github/actions/lint@bd54158ec41d8d18182eb99e516353ed5ea92858 # v1.0.1
      - name: 🔎 Reuse check
        run: make lint-reuse
        shell: bash
      - name: 🔎 Build
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: 'v2.15.4'
          args: release --clean --snapshot
          shell: bash
