name: Check build & lint

on:
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "**.yaml"
      - "**.mod"
      - "**.sum"
      - "!capm.yaml"
      - "!osc-secret.yaml"
      - "!example/**.yaml"
      - "!helm/**"
      - "Makefile"
      - "Dockerfile"
      - "!docs/src/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: 🔎 golangci-lint
        uses: outscale/goutils/.github/actions/lint@ba9b0e7bcc1ab4b8fd2c69d8b4de17d86218f5b5 # main
      - name: 🔎 Reuse check
        run: make lint-reuse
        shell: bash
      - name: 🔎 Run make build
        run: make build
        shell: bash
      - name: 🔎 Docker Lint
        run: make dockerlint
        shell: bash
