name: image-test

on: push
jobs:
  image-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout image-builder
      uses: actions/checkout@v3
      with:
        repository: 'outscale-vbr/image-builder'
        path: "add-outscale-image"
        ref: add-outscale-image
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.7'
    - uses: actions/checkout@v3
      with:
          repository: outscale-vbr/cluster-api-provider-outscale
          ref: multi-region
          path: cluster-api-provider-outscale
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
    - name: Install gh
      run: make install-gh
      working-directory: ${{ github.workspace }}/cluster-api-provider-outscale
    - name: Generate image docs
      run: make generate-image-docs
      env:
        SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
      working-directory: ${{ github.workspace }}/cluster-api-provider-outscale
