name: Unit & quickstart E2E tests

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/unit-quickstart-e2e-test.yaml"
      - "github_actions/deploy_cluster/**"
      - "**.go"
      - "go.*"
      - "**.yaml"
      - "!capm.yaml"
      - "!osc-secret.yaml"
      - "!example/**.yaml"
      - "!.github/**.yaml"
      - "!testclean/**"
      - "!helm/**"
      - "Makefile"
      - "Dockerfile"
      - "hack/*.sh"
      - "!docs/src/**"
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: ⬇️ Install Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version-file: 'go.mod'
    - name: 🧪 unit tests
      run: |
        make unit-test
        cat covers.txt
      shell: bash
  e2e-quickstart:
    runs-on: [self-hosted, linux]
    needs: [unit]
    steps:
    - name: 🩹 Safe config for 💩 DNS
      run: |
        sed 's/options /options use-vc single-request attempts:5 /' < /etc/resolv.conf > /etc/resolv.conf.new
        cat /etc/resolv.conf.new > /etc/resolv.conf
    - name: ⬇️ Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: ⬇️ Install helm
      uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5
    - name: ⬇️ Install kustomize
      uses: imranismail/setup-kustomize@53f941b41dca13ed61874bbc6b4b6e1562877530 # v3
      with:
        kustomize-version: 5.7.1
    - name: 🔎 Check IP
      id: ip
      run: |
        echo "ip=`curl -s https://api.ipify.org`" | tee $GITHUB_OUTPUT
    - name: 🔐 Set ak/sk name based on runner region
      run: .github/scripts/runneraksk.sh
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@master
      with:
        access_key: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        secret_key: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        region: ${{ env.OSC_REGION }}
        exclude_resource_types: access_key
    - name: 👷 Create k8s Kind Cluster
      id: kind
      uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1
      with:
        cluster_name: caposc
    - name: 👷 Set kubectl context
      id: kubeconfig
      run: |
        kubectl config use-context kind-caposc
    - name: ⬇️ Install Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version-file: 'go.mod'
    - name: 📦 Build and push Docker image
      run: |
        sudo apt-get update
        sudo apt install -y docker-buildx-plugin
        make docker-buildx
        make docker-push-kind
      env:
        IMG: outscale/cluster-api-outscale-controllers:${{ github.sha }}
        DOCKER_BUILDKIT: 1
    - name: 🔎 Preloader snapshot
      id: preloader
      uses: outscale/k8s-image-preloader/github_actions/preloader_snapshot@no_kubeconfig
      with:
        KUBECONTEXT: kind-caposc
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        CSI: true
    - name: 🔐 Create CAPOSC ns and credentials
      run: make credential
      shell: bash
      env:
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
    - name: 🧪 Launch quickstart e2e tests
      run: |
        from=`echo ${{ vars.IMG_UPGRADE_FROM }} | sed 's/.*kubernetes-\(v[^-]*\)-.*/\1/'`
        to=`echo ${{ vars.IMG_UPGRADE_TO }} | sed 's/.*kubernetes-\(v[^-]*\)-.*/\1/'`
        export KUBERNETES_VERSION=$from
        export KUBERNETES_VERSION_UPGRADE_FROM=$from
        export KUBERNETES_VERSION_UPGRADE_TO=$to
        make e2etest
      shell: bash
      id: e2etest
      env:
        CCM_OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        CCM_OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        CCM_OSC_REGION: ${{ env.OSC_REGION }}
        IMG: ${{ vars.REGISTRY }}/outscale/cluster-api-outscale-controllers:${{ github.sha }}
        IMG_UPGRADE_FROM: ${{ vars.IMG_UPGRADE_FROM }}
        IMG_UPGRADE_TO: ${{ vars.IMG_UPGRADE_TO }}
        PRELOAD_SNAPSHOT_ID: ${{ steps.preloader.outputs.SNAPSHOT_ID }}
    - name: 📝 Get CAPOSC state/logs
      run: |
        echo "**** pod state"
        kubectl describe po -n cluster-api-provider-outscale-system
        echo "**** pod logs"
        make logs-capo
      if: ${{ failure() && steps.e2etest.conclusion == 'failure' }}
      shell: bash
      env:
        CAPO_NAMESPACE: cluster-api-provider-outscale-system
    - name: 📝 Get cluster api logs
      run: make logs-capi
      if: ${{ failure() && steps.e2etest.conclusion == 'failure' }}
      shell: bash
      env:
        CAPI_NAMESPACE: capi-kubeadm-bootstrap-system
